"""
Spot WebSocket Market Streams

Access market data, manage accounts, and trade on Binance Spot.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from binance_common.errors import RequiredError
from binance_common.utils import ws_streams_placeholder
from binance_common.websocket import (
    WebSocketStreamBase,
    RequestStream,
    RequestStreamHandle,
)

from ..models import AggTradeResponse
from ..models import AllMarketRollingWindowTickerResponse
from ..models import AllMiniTickerResponse
from ..models import AvgPriceResponse
from ..models import BlockTradeResponse
from ..models import BookTickerResponse
from ..models import DiffBookDepthResponse
from ..models import KlineResponse
from ..models import KlineOffsetResponse
from ..models import MiniTickerResponse
from ..models import PartialBookDepthResponse
from ..models import ReferencePriceResponse
from ..models import RollingWindowTickerResponse
from ..models import TickerResponse
from ..models import TradeResponse


from ..models import AllMarketRollingWindowTickerWindowSizeEnum


from ..models import DiffBookDepthUpdateSpeedEnum

from ..models import KlineIntervalEnum


from ..models import KlineOffsetIntervalEnum


from ..models import PartialBookDepthLevelsEnum

from ..models import PartialBookDepthUpdateSpeedEnum


from ..models import RollingWindowTickerWindowSizeEnum


from typing import Optional, Union


class DefaultApi:
    """Client for DefaultApi endpoints."""

    def __init__(self, websocket_base: WebSocketStreamBase) -> None:
        self.websocket_base = websocket_base

    async def agg_trade(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Aggregate Trade Streams
            /<symbol>@aggTrade
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#agg-trade

            The Aggregate Trade Streams push trade information that is aggregated
        for a single taker order.

        Update Speed: Real-time

            Args:
                    symbol (Union[str, None]): Symbol to query
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        stream = ws_streams_placeholder(
            "/<symbol>@aggTrade".replace("/", "", 1),
            {
                "symbol": symbol,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=AggTradeResponse,
            stream_url="",
        )

    async def all_market_rolling_window_ticker(
        self,
        window_size: Union[AllMarketRollingWindowTickerWindowSizeEnum, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            All Market Rolling Window Statistics Streams
            /!ticker_<windowSize>@arr
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#all-market-rolling-window-ticker

            Rolling window ticker statistics for all market symbols, computed over
        multiple windows.

        Note that only tickers that have changed will be present in the array.

        Update Speed: 1000ms

            Args:
                    window_size (Union[AllMarketRollingWindowTickerWindowSizeEnum, None]):
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if window_size is None:
            raise RequiredError(
                field="window_size",
                error_message="Missing required parameter 'window_size'",
            )

        stream = ws_streams_placeholder(
            "/!ticker_<windowSize>@arr".replace("/", "", 1),
            {
                "window_size": window_size,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=AllMarketRollingWindowTickerResponse,
            stream_url="",
        )

    async def all_mini_ticker(
        self,
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            All Market Mini Tickers Stream
            /!miniTicker@arr
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#all-mini-ticker

            24hr rolling window mini-ticker statistics for all symbols that changed
        in an array. These are NOT the statistics of the UTC day, but a 24hr
        rolling window for the previous 24hrs. Note that only tickers that have
        changed will be present in the array.

        Update Speed: 1000ms

            Args:
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        stream = ws_streams_placeholder(
            "/!miniTicker@arr".replace("/", "", 1),
            {
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=AllMiniTickerResponse,
            stream_url="",
        )

    async def avg_price(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Average Price
            /<symbol>@avgPrice
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#avg-price

            Average price streams push changes in the average price over a fixed time interval.

        Update Speed: 1000ms

            Args:
                    symbol (Union[str, None]): Symbol to query
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        stream = ws_streams_placeholder(
            "/<symbol>@avgPrice".replace("/", "", 1),
            {
                "symbol": symbol,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=AvgPriceResponse,
            stream_url="",
        )

    async def block_trade(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Block Trade Streams
            /<symbol>@blockTrade
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#block-trade

            Block Trade Streams push block trade information in real-time.

        Update Speed: Real-time

            Args:
                    symbol (Union[str, None]): Symbol to query
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        stream = ws_streams_placeholder(
            "/<symbol>@blockTrade".replace("/", "", 1),
            {
                "symbol": symbol,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=BlockTradeResponse,
            stream_url="",
        )

    async def book_ticker(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Individual Symbol Book Ticker Streams
            /<symbol>@bookTicker
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#book-ticker

            Pushes any update to the best bid or ask's price or quantity in
        real-time for a specified symbol.

        Multiple `<symbol>@bookTicker` streams can be subscribed to over one
        connection.

        Update Speed: Real-time

            Args:
                    symbol (Union[str, None]): Symbol to query
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        stream = ws_streams_placeholder(
            "/<symbol>@bookTicker".replace("/", "", 1),
            {
                "symbol": symbol,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=BookTickerResponse,
            stream_url="",
        )

    async def diff_book_depth(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
        update_speed: Optional[DiffBookDepthUpdateSpeedEnum] = None,
    ) -> RequestStreamHandle:
        r"""
            Diff. Depth Stream
            /<symbol>@depth@<updateSpeed>
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#diff-book-depth

            Order book price and quantity depth updates used to locally manage an order book.

        Update Speed: 1000ms or 100ms

            Args:
                    symbol (Union[str, None]): Symbol to query
                    id (Optional[str] = None): Unique WebSocket request ID.
                    update_speed (Optional[DiffBookDepthUpdateSpeedEnum] = None): Optional stream update speed suffix

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        stream = ws_streams_placeholder(
            "/<symbol>@depth@<updateSpeed>".replace("/", "", 1),
            {
                "symbol": symbol,
                "id": id,
                "update_speed": update_speed,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=DiffBookDepthResponse,
            stream_url="",
        )

    async def kline(
        self,
        symbol: Union[str, None],
        interval: Union[KlineIntervalEnum, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Kline/Candlestick Streams for UTC
            /<symbol>@kline_<interval>
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#kline

            The Kline/Candlestick Stream push updates to the current
        klines/candlestick every second in `UTC+0` timezone

        Update Speed: 1000ms for `1s`, 2000ms for the other intervals

            Args:
                    symbol (Union[str, None]): Symbol to query
                    interval (Union[KlineIntervalEnum, None]):
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )
        if interval is None:
            raise RequiredError(
                field="interval", error_message="Missing required parameter 'interval'"
            )

        stream = ws_streams_placeholder(
            "/<symbol>@kline_<interval>".replace("/", "", 1),
            {
                "symbol": symbol,
                "interval": interval,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=KlineResponse,
            stream_url="",
        )

    async def kline_offset(
        self,
        symbol: Union[str, None],
        interval: Union[KlineOffsetIntervalEnum, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Kline/Candlestick Streams with timezone offset
            /<symbol>@kline_<interval>@+08:00
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#kline-offset

            The Kline/Candlestick Stream push updates to the current
        klines/candlestick every second in `UTC+8` timezone

        **Kline/Candlestick chart intervals:**

        Supported intervals: See Kline/Candlestick chart intervals

        **UTC+8 timezone offset:**
          - Kline intervals open and close in the UTC+8 timezone. For example the 1d klines will open at the beginning of the UTC+8 day, and close at the end of the UTC+8 day.
          - Note that E (event time), t (start time) and T (close time) in the payload are Unix timestamps, which are always interpreted in UTC.

        Update Speed: 1000ms for `1s`, 2000ms for the other intervals

            Args:
                    symbol (Union[str, None]): Symbol to query
                    interval (Union[KlineOffsetIntervalEnum, None]):
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )
        if interval is None:
            raise RequiredError(
                field="interval", error_message="Missing required parameter 'interval'"
            )

        stream = ws_streams_placeholder(
            "/<symbol>@kline_<interval>@+08:00".replace("/", "", 1),
            {
                "symbol": symbol,
                "interval": interval,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=KlineOffsetResponse,
            stream_url="",
        )

    async def mini_ticker(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Individual Symbol Mini Ticker Stream
            /<symbol>@miniTicker
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#mini-ticker

            24hr rolling window mini-ticker statistics. These are NOT the statistics
        of the UTC day, but a 24hr rolling window for the previous 24hrs.

        Update Speed: 1000ms

            Args:
                    symbol (Union[str, None]): Symbol to query
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        stream = ws_streams_placeholder(
            "/<symbol>@miniTicker".replace("/", "", 1),
            {
                "symbol": symbol,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=MiniTickerResponse,
            stream_url="",
        )

    async def partial_book_depth(
        self,
        symbol: Union[str, None],
        levels: Union[PartialBookDepthLevelsEnum, None],
        id: Optional[str] = None,
        update_speed: Optional[PartialBookDepthUpdateSpeedEnum] = None,
    ) -> RequestStreamHandle:
        r"""
            WebSocket Partial Book Depth Streams
            /<symbol>@depth<levels>@<updateSpeed>
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#partial-book-depth

            Top **\<levels\>** bids and asks, pushed every second.

        Update Speed: 1000ms or 100ms

            Args:
                    symbol (Union[str, None]): Symbol to query
                    levels (Union[PartialBookDepthLevelsEnum, None]):
                    id (Optional[str] = None): Unique WebSocket request ID.
                    update_speed (Optional[PartialBookDepthUpdateSpeedEnum] = None): Optional stream update speed suffix

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )
        if levels is None:
            raise RequiredError(
                field="levels", error_message="Missing required parameter 'levels'"
            )

        stream = ws_streams_placeholder(
            "/<symbol>@depth<levels>@<updateSpeed>".replace("/", "", 1),
            {
                "symbol": symbol,
                "levels": levels,
                "id": id,
                "update_speed": update_speed,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=PartialBookDepthResponse,
            stream_url="",
        )

    async def reference_price(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Reference Price Streams
            /<symbol>@referencePrice
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#reference-price

            Reference price stream for a symbol.

        Update Speed: 1000ms

            Args:
                    symbol (Union[str, None]): Symbol to query
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        stream = ws_streams_placeholder(
            "/<symbol>@referencePrice".replace("/", "", 1),
            {
                "symbol": symbol,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=ReferencePriceResponse,
            stream_url="",
        )

    async def rolling_window_ticker(
        self,
        symbol: Union[str, None],
        window_size: Union[RollingWindowTickerWindowSizeEnum, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Individual Symbol Rolling Window Statistics Streams
            /<symbol>@ticker_<windowSize>
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#rolling-window-ticker

            Rolling window ticker statistics for a single symbol, computed over
        multiple windows.

        **Note:** This stream is different from the `<symbol>@ticker` stream. The open time `"O"` always starts on a minute, while the closing time `"C"` is the current time
        of the update. As such, the effective window might be up to 59999ms wider than `<window_size>`.

        Update Speed: 1000ms

            Args:
                    symbol (Union[str, None]): Symbol to query
                    window_size (Union[RollingWindowTickerWindowSizeEnum, None]):
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )
        if window_size is None:
            raise RequiredError(
                field="window_size",
                error_message="Missing required parameter 'window_size'",
            )

        stream = ws_streams_placeholder(
            "/<symbol>@ticker_<windowSize>".replace("/", "", 1),
            {
                "symbol": symbol,
                "window_size": window_size,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=RollingWindowTickerResponse,
            stream_url="",
        )

    async def ticker(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Individual Symbol Ticker Streams
            /<symbol>@ticker
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#ticker

            24hr rolling window ticker statistics for a single symbol. These are NOT
        the statistics of the UTC day, but a 24hr rolling window for the
        previous 24hrs.

        Update Speed: 1000ms

            Args:
                    symbol (Union[str, None]): Symbol to query
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        stream = ws_streams_placeholder(
            "/<symbol>@ticker".replace("/", "", 1),
            {
                "symbol": symbol,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=TickerResponse,
            stream_url="",
        )

    async def trade(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Trade Streams
            /<symbol>@trade
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-streams/~#trade

            The Trade Streams push raw trade information; each trade has a unique
        buyer and seller.

        Update Speed: Real-time

            Args:
                    symbol (Union[str, None]): Symbol to query
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        stream = ws_streams_placeholder(
            "/<symbol>@trade".replace("/", "", 1),
            {
                "symbol": symbol,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=TradeResponse,
            stream_url="",
        )
