"""
Spot WebSocket Market Streams

Access market data, manage accounts, and trade on Binance Spot.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from enum import Enum


class AllMarketRollingWindowTickerWindowSizeEnum(Enum):
    WINDOW_SIZE_1h = "1h"
    WINDOW_SIZE_4h = "4h"
    WINDOW_SIZE_1d = "1d"


class DiffBookDepthUpdateSpeedEnum(Enum):
    UPDATE_SPEED_100ms = "100ms"


class KlineIntervalEnum(Enum):
    INTERVAL_1s = "1s"
    INTERVAL_1m = "1m"
    INTERVAL_3m = "3m"
    INTERVAL_5m = "5m"
    INTERVAL_15m = "15m"
    INTERVAL_30m = "30m"
    INTERVAL_1h = "1h"
    INTERVAL_2h = "2h"
    INTERVAL_4h = "4h"
    INTERVAL_6h = "6h"
    INTERVAL_8h = "8h"
    INTERVAL_12h = "12h"
    INTERVAL_1d = "1d"
    INTERVAL_3d = "3d"
    INTERVAL_1w = "1w"
    INTERVAL_1M = "1M"


class KlineOffsetIntervalEnum(Enum):
    INTERVAL_1s = "1s"
    INTERVAL_1m = "1m"
    INTERVAL_3m = "3m"
    INTERVAL_5m = "5m"
    INTERVAL_15m = "15m"
    INTERVAL_30m = "30m"
    INTERVAL_1h = "1h"
    INTERVAL_2h = "2h"
    INTERVAL_4h = "4h"
    INTERVAL_6h = "6h"
    INTERVAL_8h = "8h"
    INTERVAL_12h = "12h"
    INTERVAL_1d = "1d"
    INTERVAL_3d = "3d"
    INTERVAL_1w = "1w"
    INTERVAL_1M = "1M"


class PartialBookDepthLevelsEnum(Enum):
    LEVELS_5 = "5"
    LEVELS_10 = "10"
    LEVELS_20 = "20"


class PartialBookDepthUpdateSpeedEnum(Enum):
    UPDATE_SPEED_100ms = "100ms"


class RollingWindowTickerWindowSizeEnum(Enum):
    WINDOW_SIZE_1h = "1h"
    WINDOW_SIZE_4h = "4h"
    WINDOW_SIZE_1d = "1d"
