"""
Binance Wallet REST API

OpenAPI Specification for the Binance Wallet REST API
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from .account_api_trading_status_response import (
    AccountApiTradingStatusResponse as AccountApiTradingStatusResponse,
)
from .account_api_trading_status_response_data import (
    AccountApiTradingStatusResponseData as AccountApiTradingStatusResponseData,
)
from .account_api_trading_status_response_data_trigger_condition import (
    AccountApiTradingStatusResponseDataTriggerCondition as AccountApiTradingStatusResponseDataTriggerCondition,
)
from .account_info_response import AccountInfoResponse as AccountInfoResponse
from .account_status_response import AccountStatusResponse as AccountStatusResponse
from .all_coins_information_response import (
    AllCoinsInformationResponse as AllCoinsInformationResponse,
)
from .all_coins_information_response_inner import (
    AllCoinsInformationResponseInner as AllCoinsInformationResponseInner,
)
from .all_coins_information_response_inner_network_list_inner import (
    AllCoinsInformationResponseInnerNetworkListInner as AllCoinsInformationResponseInnerNetworkListInner,
)
from .asset_detail_response import AssetDetailResponse as AssetDetailResponse
from .asset_detail_response_ctr import AssetDetailResponseCTR as AssetDetailResponseCTR
from .asset_detail_response_sky import AssetDetailResponseSKY as AssetDetailResponseSKY
from .asset_dividend_record_response import (
    AssetDividendRecordResponse as AssetDividendRecordResponse,
)
from .asset_dividend_record_response_rows_inner import (
    AssetDividendRecordResponseRowsInner as AssetDividendRecordResponseRowsInner,
)
from .broker_withdraw_response import BrokerWithdrawResponse as BrokerWithdrawResponse
from .check_questionnaire_requirements_response import (
    CheckQuestionnaireRequirementsResponse as CheckQuestionnaireRequirementsResponse,
)
from .daily_account_snapshot_response import (
    DailyAccountSnapshotResponse as DailyAccountSnapshotResponse,
)
from .daily_account_snapshot_response_snapshot_vos_inner import (
    DailyAccountSnapshotResponseSnapshotVosInner as DailyAccountSnapshotResponseSnapshotVosInner,
)
from .daily_account_snapshot_response_snapshot_vos_inner_data import (
    DailyAccountSnapshotResponseSnapshotVosInnerData as DailyAccountSnapshotResponseSnapshotVosInnerData,
)
from .daily_account_snapshot_response_snapshot_vos_inner_data_assets_inner import (
    DailyAccountSnapshotResponseSnapshotVosInnerDataAssetsInner as DailyAccountSnapshotResponseSnapshotVosInnerDataAssetsInner,
)
from .daily_account_snapshot_response_snapshot_vos_inner_data_balances_inner import (
    DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner as DailyAccountSnapshotResponseSnapshotVosInnerDataBalancesInner,
)
from .daily_account_snapshot_response_snapshot_vos_inner_data_position_inner import (
    DailyAccountSnapshotResponseSnapshotVosInnerDataPositionInner as DailyAccountSnapshotResponseSnapshotVosInnerDataPositionInner,
)
from .daily_account_snapshot_response_snapshot_vos_inner_data_user_assets_inner import (
    DailyAccountSnapshotResponseSnapshotVosInnerDataUserAssetsInner as DailyAccountSnapshotResponseSnapshotVosInnerDataUserAssetsInner,
)
from .deposit_address_response import DepositAddressResponse as DepositAddressResponse
from .deposit_history_response import DepositHistoryResponse as DepositHistoryResponse
from .deposit_history_response_inner import (
    DepositHistoryResponseInner as DepositHistoryResponseInner,
)
from .deposit_history_travel_rule_response import (
    DepositHistoryTravelRuleResponse as DepositHistoryTravelRuleResponse,
)
from .deposit_history_travel_rule_response_inner import (
    DepositHistoryTravelRuleResponseInner as DepositHistoryTravelRuleResponseInner,
)
from .deposit_history_v2_response import (
    DepositHistoryV2Response as DepositHistoryV2Response,
)
from .deposit_history_v2_response_inner import (
    DepositHistoryV2ResponseInner as DepositHistoryV2ResponseInner,
)
from .deposit_history_v2_response_inner_questionnaire import (
    DepositHistoryV2ResponseInnerQuestionnaire as DepositHistoryV2ResponseInnerQuestionnaire,
)
from .dust_convert_response import DustConvertResponse as DustConvertResponse
from .dust_convert_response_transfer_result_inner import (
    DustConvertResponseTransferResultInner as DustConvertResponseTransferResultInner,
)
from .dust_convertible_assets_response import (
    DustConvertibleAssetsResponse as DustConvertibleAssetsResponse,
)
from .dust_convertible_assets_response_details_inner import (
    DustConvertibleAssetsResponseDetailsInner as DustConvertibleAssetsResponseDetailsInner,
)
from .dust_transfer_response import DustTransferResponse as DustTransferResponse
from .dust_transfer_response_transfer_result_inner import (
    DustTransferResponseTransferResultInner as DustTransferResponseTransferResultInner,
)
from .dustlog_response import DustlogResponse as DustlogResponse
from .dustlog_response_user_asset_dribblets_inner import (
    DustlogResponseUserAssetDribbletsInner as DustlogResponseUserAssetDribbletsInner,
)
from .dustlog_response_user_asset_dribblets_inner_user_asset_dribblet_details_inner import (
    DustlogResponseUserAssetDribbletsInnerUserAssetDribbletDetailsInner as DustlogResponseUserAssetDribbletsInnerUserAssetDribbletDetailsInner,
)
from .fetch_address_verification_list_response import (
    FetchAddressVerificationListResponse as FetchAddressVerificationListResponse,
)
from .fetch_address_verification_list_response_inner import (
    FetchAddressVerificationListResponseInner as FetchAddressVerificationListResponseInner,
)
from .fetch_address_verification_list_response_inner_address_questionnaire import (
    FetchAddressVerificationListResponseInnerAddressQuestionnaire as FetchAddressVerificationListResponseInnerAddressQuestionnaire,
)
from .fetch_deposit_address_list_with_network_response import (
    FetchDepositAddressListWithNetworkResponse as FetchDepositAddressListWithNetworkResponse,
)
from .fetch_deposit_address_list_with_network_response_inner import (
    FetchDepositAddressListWithNetworkResponseInner as FetchDepositAddressListWithNetworkResponseInner,
)
from .fetch_withdraw_address_list_response import (
    FetchWithdrawAddressListResponse as FetchWithdrawAddressListResponse,
)
from .fetch_withdraw_address_list_response_inner import (
    FetchWithdrawAddressListResponseInner as FetchWithdrawAddressListResponseInner,
)
from .fetch_withdraw_quota_response import (
    FetchWithdrawQuotaResponse as FetchWithdrawQuotaResponse,
)
from .funding_wallet_response import FundingWalletResponse as FundingWalletResponse
from .funding_wallet_response_inner import (
    FundingWalletResponseInner as FundingWalletResponseInner,
)
from .get_api_key_permission_response import (
    GetApiKeyPermissionResponse as GetApiKeyPermissionResponse,
)
from .get_assets_that_can_be_converted_into_bnb_response import (
    GetAssetsThatCanBeConvertedIntoBnbResponse as GetAssetsThatCanBeConvertedIntoBnbResponse,
)
from .get_assets_that_can_be_converted_into_bnb_response_details_inner import (
    GetAssetsThatCanBeConvertedIntoBnbResponseDetailsInner as GetAssetsThatCanBeConvertedIntoBnbResponseDetailsInner,
)
from .get_cloud_mining_payment_and_refund_history_response import (
    GetCloudMiningPaymentAndRefundHistoryResponse as GetCloudMiningPaymentAndRefundHistoryResponse,
)
from .get_cloud_mining_payment_and_refund_history_response_rows_inner import (
    GetCloudMiningPaymentAndRefundHistoryResponseRowsInner as GetCloudMiningPaymentAndRefundHistoryResponseRowsInner,
)
from .get_open_symbol_list_response import (
    GetOpenSymbolListResponse as GetOpenSymbolListResponse,
)
from .get_open_symbol_list_response_inner import (
    GetOpenSymbolListResponseInner as GetOpenSymbolListResponseInner,
)
from .get_spot_delist_schedule_response import (
    GetSpotDelistScheduleResponse as GetSpotDelistScheduleResponse,
)
from .get_spot_delist_schedule_response_inner import (
    GetSpotDelistScheduleResponseInner as GetSpotDelistScheduleResponseInner,
)
from .get_symbols_delist_schedule_for_spot_response import (
    GetSymbolsDelistScheduleForSpotResponse as GetSymbolsDelistScheduleForSpotResponse,
)
from .get_symbols_delist_schedule_for_spot_response_inner import (
    GetSymbolsDelistScheduleForSpotResponseInner as GetSymbolsDelistScheduleForSpotResponseInner,
)
from .one_click_arrival_deposit_apply_response import (
    OneClickArrivalDepositApplyResponse as OneClickArrivalDepositApplyResponse,
)
from .query_user_delegation_history_response import (
    QueryUserDelegationHistoryResponse as QueryUserDelegationHistoryResponse,
)
from .query_user_delegation_history_response_rows_inner import (
    QueryUserDelegationHistoryResponseRowsInner as QueryUserDelegationHistoryResponseRowsInner,
)
from .query_user_universal_transfer_history_response import (
    QueryUserUniversalTransferHistoryResponse as QueryUserUniversalTransferHistoryResponse,
)
from .query_user_universal_transfer_history_response_rows_inner import (
    QueryUserUniversalTransferHistoryResponseRowsInner as QueryUserUniversalTransferHistoryResponseRowsInner,
)
from .query_user_wallet_balance_response import (
    QueryUserWalletBalanceResponse as QueryUserWalletBalanceResponse,
)
from .query_user_wallet_balance_response_inner import (
    QueryUserWalletBalanceResponseInner as QueryUserWalletBalanceResponseInner,
)
from .submit_deposit_questionnaire_response import (
    SubmitDepositQuestionnaireResponse as SubmitDepositQuestionnaireResponse,
)
from .submit_deposit_questionnaire_travel_rule_response import (
    SubmitDepositQuestionnaireTravelRuleResponse as SubmitDepositQuestionnaireTravelRuleResponse,
)
from .submit_deposit_questionnaire_v2_response import (
    SubmitDepositQuestionnaireV2Response as SubmitDepositQuestionnaireV2Response,
)
from .system_status_response import SystemStatusResponse as SystemStatusResponse
from .toggle_bnb_burn_on_spot_trade_and_margin_interest_response import (
    ToggleBnbBurnOnSpotTradeAndMarginInterestResponse as ToggleBnbBurnOnSpotTradeAndMarginInterestResponse,
)
from .trade_fee_response import TradeFeeResponse as TradeFeeResponse
from .trade_fee_response_inner import TradeFeeResponseInner as TradeFeeResponseInner
from .user_asset_response import UserAssetResponse as UserAssetResponse
from .user_asset_response_inner import UserAssetResponseInner as UserAssetResponseInner
from .user_universal_transfer_response import (
    UserUniversalTransferResponse as UserUniversalTransferResponse,
)
from .vasp_list_response import VaspListResponse as VaspListResponse
from .vasp_list_response_inner import VaspListResponseInner as VaspListResponseInner
from .withdraw_history_response import (
    WithdrawHistoryResponse as WithdrawHistoryResponse,
)
from .withdraw_history_response_inner import (
    WithdrawHistoryResponseInner as WithdrawHistoryResponseInner,
)
from .withdraw_history_v1_response import (
    WithdrawHistoryV1Response as WithdrawHistoryV1Response,
)
from .withdraw_history_v2_response import (
    WithdrawHistoryV2Response as WithdrawHistoryV2Response,
)
from .withdraw_history_v2_response_inner import (
    WithdrawHistoryV2ResponseInner as WithdrawHistoryV2ResponseInner,
)
from .withdraw_response import WithdrawResponse as WithdrawResponse
from .withdraw_travel_rule_response import (
    WithdrawTravelRuleResponse as WithdrawTravelRuleResponse,
)
