"""
Portfolio Margin REST API

Access account information, manage margin positions, and trade with Binance Portfolio Margin.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from typing import Optional, Union
from requests import Session
from binance_common.configuration import ConfigurationRestAPI
from binance_common.errors import RequiredError
from binance_common.models import ApiResponse
from binance_common.signature import Signers
from binance_common.utils import send_request

from ..models import AccountBalanceResponse
from ..models import AccountInformationResponse
from ..models import BnbTransferResponse
from ..models import ChangeAutoRepayFuturesStatusResponse
from ..models import ChangeCmInitialLeverageResponse
from ..models import ChangeCmPositionModeResponse
from ..models import ChangeUmInitialLeverageResponse
from ..models import ChangeUmPositionModeResponse
from ..models import CmNotionalAndLeverageBracketsResponse
from ..models import FundAutoCollectionResponse
from ..models import FundCollectionByAssetResponse
from ..models import GetAutoRepayFuturesStatusResponse
from ..models import GetCmAccountDetailResponse
from ..models import GetCmCurrentPositionModeResponse
from ..models import GetCmIncomeHistoryResponse
from ..models import GetDownloadIdForUmFuturesOrderHistoryResponse
from ..models import GetDownloadIdForUmFuturesTradeHistoryResponse
from ..models import GetDownloadIdForUmFuturesTransactionHistoryResponse
from ..models import GetMarginBorrowLoanInterestHistoryResponse
from ..models import GetUmAccountDetailResponse
from ..models import GetUmAccountDetailV2Response
from ..models import GetUmCurrentPositionModeResponse
from ..models import GetUmFuturesOrderDownloadLinkByIdResponse
from ..models import GetUmFuturesTradeDownloadLinkByIdResponse
from ..models import GetUmFuturesTransactionDownloadLinkByIdResponse
from ..models import GetUmIncomeHistoryResponse
from ..models import GetUserCommissionRateForCmResponse
from ..models import GetUserCommissionRateForUmResponse
from ..models import MarginMaxBorrowResponse
from ..models import PortfolioMarginUmTradingQuantitativeRulesIndicatorsResponse
from ..models import QueryCmPositionInformationResponse
from ..models import QueryMarginLoanRecordResponse
from ..models import QueryMarginMaxWithdrawResponse
from ..models import QueryMarginRepayRecordResponse
from ..models import QueryPortfolioMarginNegativeBalanceInterestHistoryResponse
from ..models import QueryUmPositionInformationResponse
from ..models import QueryUserNegativeBalanceAutoExchangeRecordResponse
from ..models import QueryUserRateLimitResponse
from ..models import RepayFuturesNegativeBalanceResponse
from ..models import UmFuturesAccountConfigurationResponse
from ..models import UmFuturesSymbolConfigurationResponse
from ..models import UmNotionalAndLeverageBracketsResponse


from ..models import BnbTransferTransferSideEnum
from ..models import ChangeAutoRepayFuturesStatusAutoRepayEnum
from ..models import ChangeCmPositionModeDualSidePositionEnum
from ..models import ChangeUmPositionModeDualSidePositionEnum
from ..models import GetCmIncomeHistoryIncomeTypeEnum
from ..models import GetMarginBorrowLoanInterestHistoryArchivedEnum
from ..models import GetUmIncomeHistoryIncomeTypeEnum
from ..models import QueryMarginLoanRecordArchivedEnum
from ..models import QueryMarginRepayRecordArchivedEnum


class AccountApi:
    """API Client for AccountApi endpoints."""

    def __init__(
        self,
        configuration: ConfigurationRestAPI = None,
        session: Session = None,
        signer: Signers = None,
    ) -> None:
        self._configuration = configuration
        self._session = session
        self._signer = signer

    def account_balance(
        self,
        asset: Optional[str] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[AccountBalanceResponse]:
        """
                Account Balance (USER_DATA)
                GET /papi/v1/balance
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#account-balance

                Query account balance

        Weight(IP): 20

        Security Type: USER_DATA

                Args:
                    asset (Optional[str] = None):
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[AccountBalanceResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"asset": asset, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/balance",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=AccountBalanceResponse,
            is_signed=True,
            signer=self._signer,
        )

    def account_information(
        self,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[AccountInformationResponse]:
        """
                Account Information (USER_DATA)
                GET /papi/v1/account
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#account-information

                Query account information

        Weight(IP): 20

        Security Type: USER_DATA

                Args:
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[AccountInformationResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/account",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=AccountInformationResponse,
            is_signed=True,
            signer=self._signer,
        )

    def bnb_transfer(
        self,
        amount: Union[float, None],
        transfer_side: Union[BnbTransferTransferSideEnum, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[BnbTransferResponse]:
        """
                BNB transfer (TRADE)
                POST /papi/v1/bnb-transfer
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#bnb-transfer

                Transfer BNB in and out of UM

        Weight(IP): 750

        Security Type: TRADE

        Notes:
        - The endpoint can only be called 10 times per 10 minutes in a rolling manner

                Args:
                    amount (Union[float, None]):
                    transfer_side (Union[BnbTransferTransferSideEnum, None]):
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[BnbTransferResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if amount is None:
            raise RequiredError(
                field="amount", error_message="Missing required parameter 'amount'"
            )
        if transfer_side is None:
            raise RequiredError(
                field="transfer_side",
                error_message="Missing required parameter 'transfer_side'",
            )

        body = {}
        payload = {
            "amount": amount,
            "transfer_side": transfer_side,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/papi/v1/bnb-transfer",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=BnbTransferResponse,
            is_signed=True,
            signer=self._signer,
        )

    def change_auto_repay_futures_status(
        self,
        auto_repay: Union[ChangeAutoRepayFuturesStatusAutoRepayEnum, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[ChangeAutoRepayFuturesStatusResponse]:
        """
                Change Auto-repay-futures Status (TRADE)
                POST /papi/v1/repay-futures-switch
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#change-auto-repay-futures-status

                Change Auto-repay-futures Status

        Weight(IP): 750

        Security Type: TRADE

                Args:
                    auto_repay (Union[ChangeAutoRepayFuturesStatusAutoRepayEnum, None]): `false` for turn off the auto-repay futures negative balance function
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[ChangeAutoRepayFuturesStatusResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if auto_repay is None:
            raise RequiredError(
                field="auto_repay",
                error_message="Missing required parameter 'auto_repay'",
            )

        body = {}
        payload = {"auto_repay": auto_repay, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/papi/v1/repay-futures-switch",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=ChangeAutoRepayFuturesStatusResponse,
            is_signed=True,
            signer=self._signer,
        )

    def change_cm_initial_leverage(
        self,
        symbol: Union[str, None],
        leverage: Union[int, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[ChangeCmInitialLeverageResponse]:
        """
                Change CM Initial Leverage (TRADE)
                POST /papi/v1/cm/leverage
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#change-cm-initial-leverage

                Change user's initial leverage of specific symbol in CM.

        Weight(IP): 1

        Security Type: TRADE

                Args:
                    symbol (Union[str, None]):
                    leverage (Union[int, None]): target initial leverage
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[ChangeCmInitialLeverageResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )
        if leverage is None:
            raise RequiredError(
                field="leverage", error_message="Missing required parameter 'leverage'"
            )

        body = {}
        payload = {"symbol": symbol, "leverage": leverage, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/papi/v1/cm/leverage",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=ChangeCmInitialLeverageResponse,
            is_signed=True,
            signer=self._signer,
        )

    def change_cm_position_mode(
        self,
        dual_side_position: Union[ChangeCmPositionModeDualSidePositionEnum, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[ChangeCmPositionModeResponse]:
        """
                Change CM Position Mode (TRADE)
                POST /papi/v1/cm/positionSide/dual
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#change-cm-position-mode

                Change user's position mode (Hedge Mode or One-way Mode ) on EVERY symbol in CM

        Weight(IP): 1

        Security Type: TRADE

                Args:
                    dual_side_position (Union[ChangeCmPositionModeDualSidePositionEnum, None]): "true": Hedge Mode; "false": One-way Mode
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[ChangeCmPositionModeResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if dual_side_position is None:
            raise RequiredError(
                field="dual_side_position",
                error_message="Missing required parameter 'dual_side_position'",
            )

        body = {}
        payload = {"dual_side_position": dual_side_position, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/papi/v1/cm/positionSide/dual",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=ChangeCmPositionModeResponse,
            is_signed=True,
            signer=self._signer,
        )

    def change_um_initial_leverage(
        self,
        symbol: Union[str, None],
        leverage: Union[int, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[ChangeUmInitialLeverageResponse]:
        """
                Change UM Initial Leverage (TRADE)
                POST /papi/v1/um/leverage
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#change-um-initial-leverage

                Change user's initial leverage of specific symbol in UM.

        Weight(IP): 1

        Security Type: TRADE

                Args:
                    symbol (Union[str, None]):
                    leverage (Union[int, None]): target initial leverage
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[ChangeUmInitialLeverageResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )
        if leverage is None:
            raise RequiredError(
                field="leverage", error_message="Missing required parameter 'leverage'"
            )

        body = {}
        payload = {"symbol": symbol, "leverage": leverage, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/papi/v1/um/leverage",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=ChangeUmInitialLeverageResponse,
            is_signed=True,
            signer=self._signer,
        )

    def change_um_position_mode(
        self,
        dual_side_position: Union[ChangeUmPositionModeDualSidePositionEnum, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[ChangeUmPositionModeResponse]:
        """
                Change UM Position Mode (TRADE)
                POST /papi/v1/um/positionSide/dual
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#change-um-position-mode

                Change user's position mode (Hedge Mode or One-way Mode ) on EVERY symbol in UM

        Weight(IP): 1

        Security Type: TRADE

                Args:
                    dual_side_position (Union[ChangeUmPositionModeDualSidePositionEnum, None]): "true": Hedge Mode; "false": One-way Mode
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[ChangeUmPositionModeResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if dual_side_position is None:
            raise RequiredError(
                field="dual_side_position",
                error_message="Missing required parameter 'dual_side_position'",
            )

        body = {}
        payload = {"dual_side_position": dual_side_position, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/papi/v1/um/positionSide/dual",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=ChangeUmPositionModeResponse,
            is_signed=True,
            signer=self._signer,
        )

    def cm_notional_and_leverage_brackets(
        self,
        symbol: Optional[str] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[CmNotionalAndLeverageBracketsResponse]:
        """
                CM Notional and Leverage Brackets (USER_DATA)
                GET /papi/v1/cm/leverageBracket
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#cm-notional-and-leverage-brackets

                Query CM notional and leverage brackets

        Weight(IP): 1

        Security Type: USER_DATA

                Args:
                    symbol (Optional[str] = None):
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[CmNotionalAndLeverageBracketsResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"symbol": symbol, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/cm/leverageBracket",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=CmNotionalAndLeverageBracketsResponse,
            is_signed=True,
            signer=self._signer,
        )

    def fund_auto_collection(
        self,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[FundAutoCollectionResponse]:
        """
                Fund Auto-collection (TRADE)
                POST /papi/v1/auto-collection
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#fund-auto-collection

                Fund collection for Portfolio Margin

        Weight(IP): 750

        Security Type: TRADE

        Notes:
        - BNB assets will not be auto-collected.
        - Rolling window endpoint can be called at most 500 times per hour.

                Args:
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[FundAutoCollectionResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/papi/v1/auto-collection",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=FundAutoCollectionResponse,
            is_signed=True,
            signer=self._signer,
        )

    def fund_collection_by_asset(
        self,
        asset: Union[str, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[FundCollectionByAssetResponse]:
        """
                Fund Collection by Asset (TRADE)
                POST /papi/v1/asset-collection
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#fund-collection-by-asset

                Transfers specific asset from Futures Account to Margin account

        Weight(IP): 30

        Security Type: TRADE

        Notes:
        - The BNB transfer is not be supported

                Args:
                    asset (Union[str, None]):
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[FundCollectionByAssetResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if asset is None:
            raise RequiredError(
                field="asset", error_message="Missing required parameter 'asset'"
            )

        body = {}
        payload = {"asset": asset, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/papi/v1/asset-collection",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=FundCollectionByAssetResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_auto_repay_futures_status(
        self,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetAutoRepayFuturesStatusResponse]:
        """
                Get Auto-repay-futures Status (USER_DATA)
                GET /papi/v1/repay-futures-switch
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-auto-repay-futures-status

                Query Auto-repay-futures Status

        Weight(IP): 30

        Security Type: USER_DATA

                Args:
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetAutoRepayFuturesStatusResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/repay-futures-switch",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetAutoRepayFuturesStatusResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_cm_account_detail(
        self,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetCmAccountDetailResponse]:
        """
                Get CM Account Detail (USER_DATA)
                GET /papi/v1/cm/account
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-cm-account-detail

                Get current CM account asset and position information.

        Weight(IP): 5

        Security Type: USER_DATA

                Args:
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetCmAccountDetailResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/cm/account",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetCmAccountDetailResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_cm_current_position_mode(
        self,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetCmCurrentPositionModeResponse]:
        """
                Get CM Current Position Mode (USER_DATA)
                GET /papi/v1/cm/positionSide/dual
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-cm-current-position-mode

                Get user's position mode (Hedge Mode or One-way Mode ) on EVERY symbol in CM

        Weight(IP): 30

        Security Type: USER_DATA

                Args:
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetCmCurrentPositionModeResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/cm/positionSide/dual",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetCmCurrentPositionModeResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_cm_income_history(
        self,
        symbol: Optional[str] = None,
        income_type: Optional[GetCmIncomeHistoryIncomeTypeEnum] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        page: Optional[int] = None,
        limit: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetCmIncomeHistoryResponse]:
        """
                Get CM Income History (USER_DATA)
                GET /papi/v1/cm/income
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-cm-income-history

                Get CM Income History.

        Weight(IP): 30

        Security Type: USER_DATA

        Notes:
        - If `incomeType` is not sent, all kinds of flow will be returned
        - "trandId" is unique in the same "incomeType" for a user
        - The interval between `startTime` and `endTime` can not exceed 200 days:
          - If `startTime` and `endTime` are not sent, the last 200 days will be returned

                Args:
                    symbol (Optional[str] = None):
                    income_type (Optional[GetCmIncomeHistoryIncomeTypeEnum] = None):
                    start_time (Optional[int] = None): Timestamp in ms to get funding from INCLUSIVE.
                    end_time (Optional[int] = None): Timestamp in ms to get funding until INCLUSIVE.
                    page (Optional[int] = None):
                    limit (Optional[int] = None): Number of results returned.
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetCmIncomeHistoryResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "symbol": symbol,
            "income_type": income_type,
            "start_time": start_time,
            "end_time": end_time,
            "page": page,
            "limit": limit,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/cm/income",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetCmIncomeHistoryResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_download_id_for_um_futures_order_history(
        self,
        start_time: Union[int, None],
        end_time: Union[int, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetDownloadIdForUmFuturesOrderHistoryResponse]:
        """
                Get Download Id For UM Futures Order History (USER_DATA)
                GET /papi/v1/um/order/asyn
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-download-id-for-um-futures-order-history

                Get download id for UM futures order history

        Weight(IP): 1500

        Security Type: USER_DATA

        Notes:
        - Request Limitation is 10 times per month, shared by front end download page and rest api
        - The time between `startTime` and `endTime` can not be longer than 1 year

                Args:
                    start_time (Union[int, None]): Timestamp in ms
                    end_time (Union[int, None]): Timestamp in ms
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetDownloadIdForUmFuturesOrderHistoryResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if start_time is None:
            raise RequiredError(
                field="start_time",
                error_message="Missing required parameter 'start_time'",
            )
        if end_time is None:
            raise RequiredError(
                field="end_time", error_message="Missing required parameter 'end_time'"
            )

        body = {}
        payload = {
            "start_time": start_time,
            "end_time": end_time,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/order/asyn",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetDownloadIdForUmFuturesOrderHistoryResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_download_id_for_um_futures_trade_history(
        self,
        start_time: Union[int, None],
        end_time: Union[int, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetDownloadIdForUmFuturesTradeHistoryResponse]:
        """
                Get Download Id For UM Futures Trade History (USER_DATA)
                GET /papi/v1/um/trade/asyn
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-download-id-for-um-futures-trade-history

                Get download id for UM futures trade history

        Weight(IP): 1500

        Security Type: USER_DATA

        Notes:
        - Request Limitation is 5 times per month, shared by front end download page and rest api
        - The time between `startTime` and `endTime` can not be longer than 1 year

                Args:
                    start_time (Union[int, None]): Timestamp in ms
                    end_time (Union[int, None]): Timestamp in ms
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetDownloadIdForUmFuturesTradeHistoryResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if start_time is None:
            raise RequiredError(
                field="start_time",
                error_message="Missing required parameter 'start_time'",
            )
        if end_time is None:
            raise RequiredError(
                field="end_time", error_message="Missing required parameter 'end_time'"
            )

        body = {}
        payload = {
            "start_time": start_time,
            "end_time": end_time,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/trade/asyn",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetDownloadIdForUmFuturesTradeHistoryResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_download_id_for_um_futures_transaction_history(
        self,
        start_time: Union[int, None],
        end_time: Union[int, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetDownloadIdForUmFuturesTransactionHistoryResponse]:
        """
                Get Download Id For UM Futures Transaction History (USER_DATA)
                GET /papi/v1/um/income/asyn
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-download-id-for-um-futures-transaction-history

                Get download id for UM futures transaction history

        Weight(IP): 1500

        Security Type: USER_DATA

        Notes:
        - Request Limitation is 5 times per month, shared by front end download page and rest api
        - The time between `startTime` and `endTime` can not be longer than 1 year

                Args:
                    start_time (Union[int, None]): Timestamp in ms
                    end_time (Union[int, None]): Timestamp in ms
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetDownloadIdForUmFuturesTransactionHistoryResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if start_time is None:
            raise RequiredError(
                field="start_time",
                error_message="Missing required parameter 'start_time'",
            )
        if end_time is None:
            raise RequiredError(
                field="end_time", error_message="Missing required parameter 'end_time'"
            )

        body = {}
        payload = {
            "start_time": start_time,
            "end_time": end_time,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/income/asyn",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetDownloadIdForUmFuturesTransactionHistoryResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_margin_borrow_loan_interest_history(
        self,
        asset: Optional[str] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        archived: Optional[GetMarginBorrowLoanInterestHistoryArchivedEnum] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetMarginBorrowLoanInterestHistoryResponse]:
        """
                Get Margin Borrow/Loan Interest History (USER_DATA)
                GET /papi/v1/margin/marginInterestHistory
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-margin-borrow-loan-interest-history

                Get Margin Borrow/Loan Interest History

        Weight(IP): 1

        Security Type: USER_DATA

        Notes:
        - Response in descending order
        - The max interval between startTime and endTime is 30 days. It is a MUST to ensure data correctness.
        - If `startTime` and `endTime` not sent, return records of the last 7 days by default
        - If `startTime` is sent and `endTime` is not sent, the records from `startTime` to the present will be returned; if `startTime` is more than 30 days ago, the records of the past 30 days will be returned.
        - If `startTime` is not sent and `endTime` is sent, the records of the 7 days before `endTime` is returned.
        - Type in response has 5 enums:
          - `PERIODIC` interest charged per hour
          - `ON_BORROW` first interest charged on borrow
          - `PERIODIC_CONVERTED` interest charged per hour converted into BNB
          - `ON_BORROW_CONVERTED` first interest charged on borrow converted into BNB
          - `PORTFOLIO` Portfolio Margin negative balance daily interest

                Args:
                    asset (Optional[str] = None):
                    start_time (Optional[int] = None): Timestamp in ms to get funding from INCLUSIVE.
                    end_time (Optional[int] = None): Timestamp in ms to get funding until INCLUSIVE.
                    current (Optional[int] = None): Current page number.
                    size (Optional[int] = None): Number of results returned.
                    archived (Optional[GetMarginBorrowLoanInterestHistoryArchivedEnum] = None): Set to true to query archived data from 6 months ago.
                    recv_window (Optional[int] = None): The value cannot be greater than `60000`

                Returns:
                    ApiResponse[GetMarginBorrowLoanInterestHistoryResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "asset": asset,
            "start_time": start_time,
            "end_time": end_time,
            "current": current,
            "size": size,
            "archived": archived,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/margin/marginInterestHistory",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetMarginBorrowLoanInterestHistoryResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_um_account_detail(
        self,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetUmAccountDetailResponse]:
        """
                Get UM Account Detail (USER_DATA)
                GET /papi/v1/um/account
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-um-account-detail

                Get current UM account asset and position information.

        Weight(IP): 5

        Security Type: USER_DATA

                Args:
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetUmAccountDetailResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/account",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetUmAccountDetailResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_um_account_detail_v2(
        self,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetUmAccountDetailV2Response]:
        """
                Get UM Account Detail V2 (USER_DATA)
                GET /papi/v2/um/account
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-um-account-detail-v2

                Get current UM account asset and position information.

        Weight(IP): 5

        Security Type: USER_DATA

                Args:
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetUmAccountDetailV2Response]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v2/um/account",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetUmAccountDetailV2Response,
            is_signed=True,
            signer=self._signer,
        )

    def get_um_current_position_mode(
        self,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetUmCurrentPositionModeResponse]:
        """
                Get UM Current Position Mode (USER_DATA)
                GET /papi/v1/um/positionSide/dual
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-um-current-position-mode

                Get user's position mode (Hedge Mode or One-way Mode ) on EVERY symbol in UM

        Weight(IP): 30

        Security Type: USER_DATA

                Args:
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetUmCurrentPositionModeResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/positionSide/dual",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetUmCurrentPositionModeResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_um_futures_order_download_link_by_id(
        self,
        download_id: Union[str, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetUmFuturesOrderDownloadLinkByIdResponse]:
        """
                Get UM Futures Order Download Link by Id (USER_DATA)
                GET /papi/v1/um/order/asyn/id
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-um-futures-order-download-link-by-id

                Get UM futures order download link by Id

        Weight(IP): 10

        Security Type: USER_DATA

        Notes:
        - Download link expiration: 7 days

                Args:
                    download_id (Union[str, None]): get by download id api
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetUmFuturesOrderDownloadLinkByIdResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if download_id is None:
            raise RequiredError(
                field="download_id",
                error_message="Missing required parameter 'download_id'",
            )

        body = {}
        payload = {"download_id": download_id, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/order/asyn/id",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetUmFuturesOrderDownloadLinkByIdResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_um_futures_trade_download_link_by_id(
        self,
        download_id: Union[str, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetUmFuturesTradeDownloadLinkByIdResponse]:
        """
                Get UM Futures Trade Download Link by Id (USER_DATA)
                GET /papi/v1/um/trade/asyn/id
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-um-futures-trade-download-link-by-id

                Get UM futures trade download link by Id

        Weight(IP): 10

        Security Type: USER_DATA

        Notes:
        - Download link expiration: 7 days

                Args:
                    download_id (Union[str, None]): get by download id api
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetUmFuturesTradeDownloadLinkByIdResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if download_id is None:
            raise RequiredError(
                field="download_id",
                error_message="Missing required parameter 'download_id'",
            )

        body = {}
        payload = {"download_id": download_id, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/trade/asyn/id",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetUmFuturesTradeDownloadLinkByIdResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_um_futures_transaction_download_link_by_id(
        self,
        download_id: Union[str, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetUmFuturesTransactionDownloadLinkByIdResponse]:
        """
                Get UM Futures Transaction Download Link by Id (USER_DATA)
                GET /papi/v1/um/income/asyn/id
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-um-futures-transaction-download-link-by-id

                Get UM futures Transaction download link by Id

        Weight(IP): 10

        Security Type: USER_DATA

        Notes:
        - Download link expiration: 7 days

                Args:
                    download_id (Union[str, None]): get by download id api
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetUmFuturesTransactionDownloadLinkByIdResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if download_id is None:
            raise RequiredError(
                field="download_id",
                error_message="Missing required parameter 'download_id'",
            )

        body = {}
        payload = {"download_id": download_id, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/income/asyn/id",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetUmFuturesTransactionDownloadLinkByIdResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_um_income_history(
        self,
        symbol: Optional[str] = None,
        income_type: Optional[GetUmIncomeHistoryIncomeTypeEnum] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        page: Optional[int] = None,
        limit: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetUmIncomeHistoryResponse]:
        """
                Get UM Income History (USER_DATA)
                GET /papi/v1/um/income
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-um-income-history

                Get UM Income History.

        Weight(IP): 30

        Security Type: USER_DATA

        Notes:
        - If neither `startTime` nor `endTime` is sent, the recent 7-day data will be returned.
        - If `incomeType` is not sent, all kinds of flow will be returned
        - "trandId" is unique in the same incomeType for a user
        - Income history only contains data for the last three months

                Args:
                    symbol (Optional[str] = None):
                    income_type (Optional[GetUmIncomeHistoryIncomeTypeEnum] = None): Income type.
                    start_time (Optional[int] = None): Timestamp in ms to get funding from INCLUSIVE.
                    end_time (Optional[int] = None): Timestamp in ms to get funding until INCLUSIVE.
                    page (Optional[int] = None): Page number.
                    limit (Optional[int] = None): Number of results returned.
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetUmIncomeHistoryResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "symbol": symbol,
            "income_type": income_type,
            "start_time": start_time,
            "end_time": end_time,
            "page": page,
            "limit": limit,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/income",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetUmIncomeHistoryResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_user_commission_rate_for_cm(
        self,
        symbol: Union[str, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetUserCommissionRateForCmResponse]:
        """
                Get User Commission Rate for CM (USER_DATA)
                GET /papi/v1/cm/commissionRate
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-user-commission-rate-for-cm

                Get User Commission Rate for CM

        Weight(IP): 20

        Security Type: USER_DATA

                Args:
                    symbol (Union[str, None]): Symbol
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetUserCommissionRateForCmResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        body = {}
        payload = {"symbol": symbol, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/cm/commissionRate",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetUserCommissionRateForCmResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_user_commission_rate_for_um(
        self,
        symbol: Union[str, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetUserCommissionRateForUmResponse]:
        """
                Get User Commission Rate for UM (USER_DATA)
                GET /papi/v1/um/commissionRate
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-user-commission-rate-for-um

                Get User Commission Rate for UM

        Weight(IP): 20

        Security Type: USER_DATA

                Args:
                    symbol (Union[str, None]): Symbol
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[GetUserCommissionRateForUmResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        body = {}
        payload = {"symbol": symbol, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/commissionRate",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetUserCommissionRateForUmResponse,
            is_signed=True,
            signer=self._signer,
        )

    def margin_max_borrow(
        self,
        asset: Union[str, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[MarginMaxBorrowResponse]:
        """
                Margin Max Borrow (USER_DATA)
                GET /papi/v1/margin/maxBorrowable
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#margin-max-borrow

                Query margin max borrow

        Weight(IP): 5

        Security Type: USER_DATA

                Args:
                    asset (Union[str, None]):
                    recv_window (Optional[int] = None): The value cannot be greater than `60000`

                Returns:
                    ApiResponse[MarginMaxBorrowResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if asset is None:
            raise RequiredError(
                field="asset", error_message="Missing required parameter 'asset'"
            )

        body = {}
        payload = {"asset": asset, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/margin/maxBorrowable",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=MarginMaxBorrowResponse,
            is_signed=True,
            signer=self._signer,
        )

    def portfolio_margin_um_trading_quantitative_rules_indicators(
        self,
        symbol: Optional[str] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[PortfolioMarginUmTradingQuantitativeRulesIndicatorsResponse]:
        """
                Portfolio Margin UM Trading Quantitative Rules Indicators (USER_DATA)
                GET /papi/v1/um/apiTradingStatus
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#portfolio-margin-um-trading-quantitative-rules-indicators

                Portfolio Margin UM Trading Quantitative Rules Indicators

        Weight: - 1 for a single `symbol`
        - 10 when `symbol` is omitted

        Security Type: USER_DATA

                Args:
                    symbol (Optional[str] = None):
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[PortfolioMarginUmTradingQuantitativeRulesIndicatorsResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"symbol": symbol, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/apiTradingStatus",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=PortfolioMarginUmTradingQuantitativeRulesIndicatorsResponse,
            is_signed=True,
            signer=self._signer,
        )

    def query_cm_position_information(
        self,
        margin_asset: Optional[str] = None,
        pair: Optional[str] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[QueryCmPositionInformationResponse]:
        """
                Query CM Position Information (USER_DATA)
                GET /papi/v1/cm/positionRisk
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#query-cm-position-information

                Get current CM position information.

        Weight(IP): 1

        Security Type: USER_DATA

        Notes:
        - If neither `marginAsset` nor `pair` is sent, positions of all symbols with `TRADING` status will be returned.
        - for One-way Mode user, the response will only show the "BOTH" positions
        - for Hedge Mode user, the response will show "LONG", and "SHORT" positions. **Note**
        - Please use with user data stream `ACCOUNT_UPDATE` to meet your timeliness and accuracy needs.

                Args:
                    margin_asset (Optional[str] = None):
                    pair (Optional[str] = None):
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[QueryCmPositionInformationResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "margin_asset": margin_asset,
            "pair": pair,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/cm/positionRisk",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=QueryCmPositionInformationResponse,
            is_signed=True,
            signer=self._signer,
        )

    def query_margin_loan_record(
        self,
        asset: Union[str, None],
        tx_id: Optional[int] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        archived: Optional[QueryMarginLoanRecordArchivedEnum] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[QueryMarginLoanRecordResponse]:
        """
                Query Margin Loan Record (USER_DATA)
                GET /papi/v1/margin/marginLoan
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#query-margin-loan-record

                Query margin loan record

        Weight(IP): 10

        Security Type: USER_DATA

        Notes:
        - txId or startTime must be sent. txId takes precedence.
        - Response in descending order
        - The max interval between `startTime` and `endTime` is 30 days.
        - If `startTime` and `endTime` not sent, return records of the last 7 days by default
        - Set `archived` to `true` to query data from 6 months ago

                Args:
                    asset (Union[str, None]):
                    tx_id (Optional[int] = None): the `tranId` in `POST/papi/v1/marginLoan`
                    start_time (Optional[int] = None): Timestamp in ms to get funding from INCLUSIVE.
                    end_time (Optional[int] = None): Timestamp in ms to get funding until INCLUSIVE.
                    current (Optional[int] = None): Current page number.
                    size (Optional[int] = None): Number of results returned.
                    archived (Optional[QueryMarginLoanRecordArchivedEnum] = None): Set to true to query archived data from 6 months ago.
                    recv_window (Optional[int] = None): The value cannot be greater than 60000

                Returns:
                    ApiResponse[QueryMarginLoanRecordResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if asset is None:
            raise RequiredError(
                field="asset", error_message="Missing required parameter 'asset'"
            )

        body = {}
        payload = {
            "asset": asset,
            "tx_id": tx_id,
            "start_time": start_time,
            "end_time": end_time,
            "current": current,
            "size": size,
            "archived": archived,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/margin/marginLoan",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=QueryMarginLoanRecordResponse,
            is_signed=True,
            signer=self._signer,
        )

    def query_margin_max_withdraw(
        self,
        asset: Union[str, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[QueryMarginMaxWithdrawResponse]:
        """
                Query Margin Max Withdraw (USER_DATA)
                GET /papi/v1/margin/maxWithdraw
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#query-margin-max-withdraw

                Query Margin Max Withdraw

        Weight(IP): 5

        Security Type: USER_DATA

                Args:
                    asset (Union[str, None]):
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[QueryMarginMaxWithdrawResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if asset is None:
            raise RequiredError(
                field="asset", error_message="Missing required parameter 'asset'"
            )

        body = {}
        payload = {"asset": asset, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/margin/maxWithdraw",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=QueryMarginMaxWithdrawResponse,
            is_signed=True,
            signer=self._signer,
        )

    def query_margin_repay_record(
        self,
        asset: Union[str, None],
        tx_id: Optional[int] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        archived: Optional[QueryMarginRepayRecordArchivedEnum] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[QueryMarginRepayRecordResponse]:
        """
                Query Margin repay Record (USER_DATA)
                GET /papi/v1/margin/repayLoan
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#query-margin-repay-record

                Query margin repay record.

        Weight(IP): 10

        Security Type: USER_DATA

        Notes:
        - txId or startTime must be sent. txId takes precedence.
        - Response in descending order
        - The max interval between `startTime` and `endTime` is 30 days.
        - If `startTime` and `endTime` not sent, return records of the last 7 days by default
        - Set `archived` to `true` to query data from 6 months ago

                Args:
                    asset (Union[str, None]):
                    tx_id (Optional[int] = None): the `tranId` in `POST /papi/v1/repayLoan`
                    start_time (Optional[int] = None): Timestamp in ms to get funding from INCLUSIVE.
                    end_time (Optional[int] = None): Timestamp in ms to get funding until INCLUSIVE.
                    current (Optional[int] = None): Current page number.
                    size (Optional[int] = None): Number of results returned.
                    archived (Optional[QueryMarginRepayRecordArchivedEnum] = None): Set to true to query archived data from 6 months ago.
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[QueryMarginRepayRecordResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if asset is None:
            raise RequiredError(
                field="asset", error_message="Missing required parameter 'asset'"
            )

        body = {}
        payload = {
            "asset": asset,
            "tx_id": tx_id,
            "start_time": start_time,
            "end_time": end_time,
            "current": current,
            "size": size,
            "archived": archived,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/margin/repayLoan",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=QueryMarginRepayRecordResponse,
            is_signed=True,
            signer=self._signer,
        )

    def query_portfolio_margin_negative_balance_interest_history(
        self,
        asset: Optional[str] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[QueryPortfolioMarginNegativeBalanceInterestHistoryResponse]:
        """
                Query Portfolio Margin Negative Balance Interest History (USER_DATA)
                GET /papi/v1/portfolio/interest-history
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#query-portfolio-margin-negative-balance-interest-history

                Query interest history of negative balance for portfolio margin.

        Weight(IP): 50

        Security Type: USER_DATA

        Notes:
        - Results are returned in descending order.
        - The query range cannot exceed 30 days to ensure data correctness.
        - If both `startTime` and `endTime` are omitted, the most recent 7 days are returned by default.
        - If `startTime` is provided but `endTime` is omitted, records from `startTime` to now are returned; if that exceeds 30 days, only the most recent 30 days are returned.
        - If `endTime` is provided but `startTime` is omitted, records from the 7 days before `endTime` are returned.

                Args:
                    asset (Optional[str] = None):
                    start_time (Optional[int] = None): Timestamp in ms to get funding from INCLUSIVE.
                    end_time (Optional[int] = None): Timestamp in ms to get funding until INCLUSIVE.
                    size (Optional[int] = None): Number of results returned.
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[QueryPortfolioMarginNegativeBalanceInterestHistoryResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "asset": asset,
            "start_time": start_time,
            "end_time": end_time,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/portfolio/interest-history",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=QueryPortfolioMarginNegativeBalanceInterestHistoryResponse,
            is_signed=True,
            signer=self._signer,
        )

    def query_um_position_information(
        self,
        symbol: Optional[str] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[QueryUmPositionInformationResponse]:
        """
                Query UM Position Information (USER_DATA)
                GET /papi/v1/um/positionRisk
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#query-um-position-information

                Get current UM position information.

        Weight(IP): 5

        Security Type: USER_DATA

        Notes:
        - Please use with account push event `ACCOUNT_UPDATE` for timeliness and accuracy.
        - In One-way Mode, only positions with side `BOTH` are shown.
        - In Hedge Mode, positions with sides `BOTH`, `LONG`, and `SHORT` are shown.

                Args:
                    symbol (Optional[str] = None):
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[QueryUmPositionInformationResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"symbol": symbol, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/positionRisk",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=QueryUmPositionInformationResponse,
            is_signed=True,
            signer=self._signer,
        )

    def query_user_negative_balance_auto_exchange_record(
        self,
        start_time: Union[int, None],
        end_time: Union[int, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[QueryUserNegativeBalanceAutoExchangeRecordResponse]:
        """
                Query User Negative Balance Auto Exchange Record (USER_DATA)
                GET /papi/v1/portfolio/negative-balance-exchange-record
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#query-user-negative-balance-auto-exchange-record

                Query user negative balance auto exchange record

        Weight(IP): 100

        Security Type: USER_DATA

        Notes:
        - Response in descending order
        - The max interval between `startTime` and `endTime` is 3 months.

                Args:
                    start_time (Union[int, None]):
                    end_time (Union[int, None]):
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[QueryUserNegativeBalanceAutoExchangeRecordResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if start_time is None:
            raise RequiredError(
                field="start_time",
                error_message="Missing required parameter 'start_time'",
            )
        if end_time is None:
            raise RequiredError(
                field="end_time", error_message="Missing required parameter 'end_time'"
            )

        body = {}
        payload = {
            "start_time": start_time,
            "end_time": end_time,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/portfolio/negative-balance-exchange-record",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=QueryUserNegativeBalanceAutoExchangeRecordResponse,
            is_signed=True,
            signer=self._signer,
        )

    def query_user_rate_limit(
        self,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[QueryUserRateLimitResponse]:
        """
                Query User Rate Limit (USER_DATA)
                GET /papi/v1/rateLimit/order
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#query-user-rate-limit

                Query User Rate Limit

        Weight(IP): 1

        Security Type: USER_DATA

                Args:
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[QueryUserRateLimitResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/rateLimit/order",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=QueryUserRateLimitResponse,
            is_signed=True,
            signer=self._signer,
        )

    def repay_futures_negative_balance(
        self,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[RepayFuturesNegativeBalanceResponse]:
        """
                Repay futures Negative Balance (USER_DATA)
                POST /papi/v1/repay-futures-negative-balance
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#repay-futures-negative-balance

                Repay futures Negative Balance

        Weight(IP): 750

        Security Type: USER_DATA

                Args:
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[RepayFuturesNegativeBalanceResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/papi/v1/repay-futures-negative-balance",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=RepayFuturesNegativeBalanceResponse,
            is_signed=True,
            signer=self._signer,
        )

    def um_futures_account_configuration(
        self,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[UmFuturesAccountConfigurationResponse]:
        """
                UM Futures Account Configuration (USER_DATA)
                GET /papi/v1/um/accountConfig
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#um-futures-account-configuration

                Query UM Futures account configuration

        Weight(IP): 5

        Security Type: USER_DATA

                Args:
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[UmFuturesAccountConfigurationResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/accountConfig",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=UmFuturesAccountConfigurationResponse,
            is_signed=True,
            signer=self._signer,
        )

    def um_futures_symbol_configuration(
        self,
        symbol: Optional[str] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[UmFuturesSymbolConfigurationResponse]:
        """
                UM Futures Symbol Configuration (USER_DATA)
                GET /papi/v1/um/symbolConfig
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#um-futures-symbol-configuration

                Get current UM account symbol configuration.

        Weight(IP): 5

        Security Type: USER_DATA

                Args:
                    symbol (Optional[str] = None): Symbol
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[UmFuturesSymbolConfigurationResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"symbol": symbol, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/symbolConfig",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=UmFuturesSymbolConfigurationResponse,
            is_signed=True,
            signer=self._signer,
        )

    def um_notional_and_leverage_brackets(
        self,
        symbol: Optional[str] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[UmNotionalAndLeverageBracketsResponse]:
        """
                UM Notional and Leverage Brackets (USER_DATA)
                GET /papi/v1/um/leverageBracket
                https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#um-notional-and-leverage-brackets

                Query UM notional and leverage brackets

        Weight(IP): 1

        Security Type: USER_DATA

                Args:
                    symbol (Optional[str] = None):
                    recv_window (Optional[int] = None):

                Returns:
                    ApiResponse[UmNotionalAndLeverageBracketsResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"symbol": symbol, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/papi/v1/um/leverageBracket",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=UmNotionalAndLeverageBracketsResponse,
            is_signed=True,
            signer=self._signer,
        )
