"""
Algo Trading REST API

Programmatic access to Binance’s execution algorithms for creating and managing Spot and Futures algo orders.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from enum import Enum


class QueryHistoricalAlgoOrdersFutureAlgoSideEnum(Enum):
    BUY = "BUY"
    SELL = "SELL"


class TimeWeightedAveragePriceFutureAlgoSideEnum(Enum):
    BUY = "BUY"
    SELL = "SELL"


class TimeWeightedAveragePriceFutureAlgoPositionSideEnum(Enum):
    BOTH = "BOTH"
    LONG = "LONG"
    SHORT = "SHORT"


class VolumeParticipationFutureAlgoSideEnum(Enum):
    BUY = "BUY"
    SELL = "SELL"


class VolumeParticipationFutureAlgoUrgencyEnum(Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class VolumeParticipationFutureAlgoPositionSideEnum(Enum):
    BOTH = "BOTH"
    LONG = "LONG"
    SHORT = "SHORT"


class QueryHistoricalAlgoOrdersSpotAlgoSideEnum(Enum):
    BUY = "BUY"
    SELL = "SELL"


class TimeWeightedAveragePriceSpotAlgoSideEnum(Enum):
    BUY = "BUY"
    SELL = "SELL"
