# coding: utf-8

"""
Margin REST API

Access account information, borrow and repay assets, and trade with Binance Margin.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class QueryMarginAccountsOpenOrdersResponseInner(BaseModel):
    """
    QueryMarginAccountsOpenOrdersResponseInner
    """  # noqa: E501

    client_order_id: Optional[StrictStr] = Field(
        default=None, description="client Order Id.", alias="clientOrderId"
    )
    cummulative_quote_qty: Optional[StrictStr] = Field(
        default=None, description="cummulative Quote Qty.", alias="cummulativeQuoteQty"
    )
    executed_qty: Optional[StrictStr] = Field(
        default=None, description="executed Qty.", alias="executedQty"
    )
    iceberg_qty: Optional[StrictStr] = Field(
        default=None, description="iceberg Qty.", alias="icebergQty"
    )
    is_working: Optional[StrictBool] = Field(
        default=None, description="is Working.", alias="isWorking"
    )
    order_id: Optional[StrictInt] = Field(
        default=None, description="order Id.", alias="orderId"
    )
    orig_qty: Optional[StrictStr] = Field(
        default=None, description="orig Qty.", alias="origQty"
    )
    price: Optional[StrictStr] = Field(default=None, description="price.")
    side: Optional[StrictStr] = Field(default=None, description="side.")
    status: Optional[StrictStr] = Field(default=None, description="status.")
    stop_price: Optional[StrictStr] = Field(
        default=None, description="stop Price.", alias="stopPrice"
    )
    symbol: Optional[StrictStr] = Field(default=None, description="symbol.")
    is_isolated: Optional[StrictBool] = Field(
        default=None, description="is Isolated.", alias="isIsolated"
    )
    time: Optional[StrictInt] = Field(default=None, description="time.")
    time_in_force: Optional[StrictStr] = Field(
        default=None, description="time In Force.", alias="timeInForce"
    )
    type: Optional[StrictStr] = Field(default=None, description="type.")
    self_trade_prevention_mode: Optional[StrictStr] = Field(
        default=None,
        description="self Trade Prevention Mode.",
        alias="selfTradePreventionMode",
    )
    update_time: Optional[StrictInt] = Field(
        default=None, description="update Time.", alias="updateTime"
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "clientOrderId",
        "cummulativeQuoteQty",
        "executedQty",
        "icebergQty",
        "isWorking",
        "orderId",
        "origQty",
        "price",
        "side",
        "status",
        "stopPrice",
        "symbol",
        "isIsolated",
        "time",
        "timeInForce",
        "type",
        "selfTradePreventionMode",
        "updateTime",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueryMarginAccountsOpenOrdersResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueryMarginAccountsOpenOrdersResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "clientOrderId": obj.get("clientOrderId"),
                "cummulativeQuoteQty": obj.get("cummulativeQuoteQty"),
                "executedQty": obj.get("executedQty"),
                "icebergQty": obj.get("icebergQty"),
                "isWorking": obj.get("isWorking"),
                "orderId": obj.get("orderId"),
                "origQty": obj.get("origQty"),
                "price": obj.get("price"),
                "side": obj.get("side"),
                "status": obj.get("status"),
                "stopPrice": obj.get("stopPrice"),
                "symbol": obj.get("symbol"),
                "isIsolated": obj.get("isIsolated"),
                "time": obj.get("time"),
                "timeInForce": obj.get("timeInForce"),
                "type": obj.get("type"),
                "selfTradePreventionMode": obj.get("selfTradePreventionMode"),
                "updateTime": obj.get("updateTime"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
