"""
Binance Crypto Loan REST API

OpenAPI Specification for the Binance Crypto Loan REST API
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from .check_collateral_repay_rate_response import (
    CheckCollateralRepayRateResponse as CheckCollateralRepayRateResponse,
)
from .check_collateral_repay_rate_stable_rate_response import (
    CheckCollateralRepayRateStableRateResponse as CheckCollateralRepayRateStableRateResponse,
)
from .flexible_loan_adjust_ltv_response import (
    FlexibleLoanAdjustLtvResponse as FlexibleLoanAdjustLtvResponse,
)
from .flexible_loan_borrow_response import (
    FlexibleLoanBorrowResponse as FlexibleLoanBorrowResponse,
)
from .flexible_loan_repay_response import (
    FlexibleLoanRepayResponse as FlexibleLoanRepayResponse,
)
from .get_crypto_loans_income_history_response import (
    GetCryptoLoansIncomeHistoryResponse as GetCryptoLoansIncomeHistoryResponse,
)
from .get_crypto_loans_income_history_response_inner import (
    GetCryptoLoansIncomeHistoryResponseInner as GetCryptoLoansIncomeHistoryResponseInner,
)
from .get_flexible_loan_assets_data_response import (
    GetFlexibleLoanAssetsDataResponse as GetFlexibleLoanAssetsDataResponse,
)
from .get_flexible_loan_assets_data_response_rows_inner import (
    GetFlexibleLoanAssetsDataResponseRowsInner as GetFlexibleLoanAssetsDataResponseRowsInner,
)
from .get_flexible_loan_borrow_history_response import (
    GetFlexibleLoanBorrowHistoryResponse as GetFlexibleLoanBorrowHistoryResponse,
)
from .get_flexible_loan_borrow_history_response_rows_inner import (
    GetFlexibleLoanBorrowHistoryResponseRowsInner as GetFlexibleLoanBorrowHistoryResponseRowsInner,
)
from .get_flexible_loan_collateral_assets_data_response import (
    GetFlexibleLoanCollateralAssetsDataResponse as GetFlexibleLoanCollateralAssetsDataResponse,
)
from .get_flexible_loan_collateral_assets_data_response_rows_inner import (
    GetFlexibleLoanCollateralAssetsDataResponseRowsInner as GetFlexibleLoanCollateralAssetsDataResponseRowsInner,
)
from .get_flexible_loan_interest_rate_history_response import (
    GetFlexibleLoanInterestRateHistoryResponse as GetFlexibleLoanInterestRateHistoryResponse,
)
from .get_flexible_loan_interest_rate_history_response_rows_inner import (
    GetFlexibleLoanInterestRateHistoryResponseRowsInner as GetFlexibleLoanInterestRateHistoryResponseRowsInner,
)
from .get_flexible_loan_liquidation_history_response import (
    GetFlexibleLoanLiquidationHistoryResponse as GetFlexibleLoanLiquidationHistoryResponse,
)
from .get_flexible_loan_liquidation_history_response_rows_inner import (
    GetFlexibleLoanLiquidationHistoryResponseRowsInner as GetFlexibleLoanLiquidationHistoryResponseRowsInner,
)
from .get_flexible_loan_ltv_adjustment_history_response import (
    GetFlexibleLoanLtvAdjustmentHistoryResponse as GetFlexibleLoanLtvAdjustmentHistoryResponse,
)
from .get_flexible_loan_ltv_adjustment_history_response_rows_inner import (
    GetFlexibleLoanLtvAdjustmentHistoryResponseRowsInner as GetFlexibleLoanLtvAdjustmentHistoryResponseRowsInner,
)
from .get_flexible_loan_ongoing_orders_response import (
    GetFlexibleLoanOngoingOrdersResponse as GetFlexibleLoanOngoingOrdersResponse,
)
from .get_flexible_loan_ongoing_orders_response_rows_inner import (
    GetFlexibleLoanOngoingOrdersResponseRowsInner as GetFlexibleLoanOngoingOrdersResponseRowsInner,
)
from .get_flexible_loan_repayment_history_response import (
    GetFlexibleLoanRepaymentHistoryResponse as GetFlexibleLoanRepaymentHistoryResponse,
)
from .get_flexible_loan_repayment_history_response_rows_inner import (
    GetFlexibleLoanRepaymentHistoryResponseRowsInner as GetFlexibleLoanRepaymentHistoryResponseRowsInner,
)
from .get_loan_borrow_history_response import (
    GetLoanBorrowHistoryResponse as GetLoanBorrowHistoryResponse,
)
from .get_loan_borrow_history_response_rows_inner import (
    GetLoanBorrowHistoryResponseRowsInner as GetLoanBorrowHistoryResponseRowsInner,
)
from .get_loan_ltv_adjustment_history_response import (
    GetLoanLtvAdjustmentHistoryResponse as GetLoanLtvAdjustmentHistoryResponse,
)
from .get_loan_ltv_adjustment_history_response_rows_inner import (
    GetLoanLtvAdjustmentHistoryResponseRowsInner as GetLoanLtvAdjustmentHistoryResponseRowsInner,
)
from .get_loan_repayment_history_response import (
    GetLoanRepaymentHistoryResponse as GetLoanRepaymentHistoryResponse,
)
from .get_loan_repayment_history_response_rows_inner import (
    GetLoanRepaymentHistoryResponseRowsInner as GetLoanRepaymentHistoryResponseRowsInner,
)
