"""
Binance Derivatives Trading Options REST API

OpenAPI Specification for the Binance Derivatives Trading Options REST API
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from enum import Enum


class NewBlockTradeOrderSideEnum(Enum):
    BUY = "BUY"
    SELL = "SELL"


class NewOrderSideEnum(Enum):
    BUY = "BUY"
    SELL = "SELL"


class NewOrderTypeEnum(Enum):
    LIMIT = "LIMIT"


class NewOrderTimeInForceEnum(Enum):
    GTC = "GTC"
    IOC = "IOC"
    FOK = "FOK"


class NewOrderNewOrderRespTypeEnum(Enum):
    ACK = "ACK"
    RESULT = "RESULT"
