"""
Wallet REST API

Query balances, manage assets, and perform wallet operations via the Binance Wallet API.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from .rest_api import WalletRestAPI

__all__ = ["WalletRestAPI"]
