# coding: utf-8

"""
Binance Derivatives Trading Portfolio Margin REST API

OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin REST API
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class AccountInformationResponse(BaseModel):
    """
    AccountInformationResponse
    """  # noqa: E501

    uni_mmr: Optional[StrictStr] = Field(default=None, alias="uniMMR")
    account_equity: Optional[StrictStr] = Field(default=None, alias="accountEquity")
    actual_equity: Optional[StrictStr] = Field(default=None, alias="actualEquity")
    account_initial_margin: Optional[StrictStr] = Field(
        default=None, alias="accountInitialMargin"
    )
    account_maint_margin: Optional[StrictStr] = Field(
        default=None, alias="accountMaintMargin"
    )
    account_status: Optional[StrictStr] = Field(default=None, alias="accountStatus")
    virtual_max_withdraw_amount: Optional[StrictStr] = Field(
        default=None, alias="virtualMaxWithdrawAmount"
    )
    total_available_balance: Optional[StrictStr] = Field(
        default=None, alias="totalAvailableBalance"
    )
    total_margin_open_loss: Optional[StrictStr] = Field(
        default=None, alias="totalMarginOpenLoss"
    )
    update_time: Optional[StrictInt] = Field(default=None, alias="updateTime")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "uniMMR",
        "accountEquity",
        "actualEquity",
        "accountInitialMargin",
        "accountMaintMargin",
        "accountStatus",
        "virtualMaxWithdrawAmount",
        "totalAvailableBalance",
        "totalMarginOpenLoss",
        "updateTime",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountInformationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountInformationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "uniMMR": obj.get("uniMMR"),
                "accountEquity": obj.get("accountEquity"),
                "actualEquity": obj.get("actualEquity"),
                "accountInitialMargin": obj.get("accountInitialMargin"),
                "accountMaintMargin": obj.get("accountMaintMargin"),
                "accountStatus": obj.get("accountStatus"),
                "virtualMaxWithdrawAmount": obj.get("virtualMaxWithdrawAmount"),
                "totalAvailableBalance": obj.get("totalAvailableBalance"),
                "totalMarginOpenLoss": obj.get("totalMarginOpenLoss"),
                "updateTime": obj.get("updateTime"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
