# coding: utf-8

"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class GetTokenTradingInfoResponseDataInner(BaseModel):
    """
    GetTokenTradingInfoResponseDataInner
    """  # noqa: E501

    binance_chain_id: Optional[StrictStr] = Field(
        default=None, description="Chain unique identifier.", alias="binanceChainId"
    )
    token_contract_address: Optional[StrictStr] = Field(
        default=None,
        description="Token contract address.",
        alias="tokenContractAddress",
    )
    price: Optional[StrictStr] = Field(
        default=None, description="Latest token price, denominated in USD."
    )
    time: Optional[StrictInt] = Field(
        default=None,
        description="Token price observation time, Unix millisecond timestamp.",
    )
    market_cap: Optional[StrictStr] = Field(
        default=None,
        description="Token market cap, denominated in USD.",
        alias="marketCap",
    )
    price_change5_m: Optional[StrictStr] = Field(
        default=None,
        description='5-minute price change percentage. "0.12" means a 0.12% increase.',
        alias="priceChange5M",
    )
    price_change1_h: Optional[StrictStr] = Field(
        default=None,
        description='1-hour price change percentage. "1.05" means a 1.05% increase.',
        alias="priceChange1H",
    )
    price_change4_h: Optional[StrictStr] = Field(
        default=None,
        description='4-hour price change percentage. "2.30" means a 2.30% increase.',
        alias="priceChange4H",
    )
    price_change24_h: Optional[StrictStr] = Field(
        default=None,
        description='24-hour price change percentage. "-0.85" means a 0.85% decrease.',
        alias="priceChange24H",
    )
    volume5_m: Optional[StrictStr] = Field(
        default=None,
        description="Trading volume in the last 5 minutes, denominated in USD.",
        alias="volume5M",
    )
    volume1_h: Optional[StrictStr] = Field(
        default=None,
        description="Trading volume in the last 1 hour, denominated in USD.",
        alias="volume1H",
    )
    volume4_h: Optional[StrictStr] = Field(
        default=None,
        description="Trading volume in the last 4 hours, denominated in USD.",
        alias="volume4H",
    )
    volume24_h: Optional[StrictStr] = Field(
        default=None,
        description="Trading volume in the last 24 hours, denominated in USD.",
        alias="volume24H",
    )
    buy_volume5_m: Optional[StrictStr] = Field(
        default=None,
        description="Buy volume in the last 5 minutes, denominated in USD.",
        alias="buyVolume5M",
    )
    buy_volume1_h: Optional[StrictStr] = Field(
        default=None,
        description="Buy volume in the last 1 hour, denominated in USD.",
        alias="buyVolume1H",
    )
    buy_volume4_h: Optional[StrictStr] = Field(
        default=None,
        description="Buy volume in the last 4 hours, denominated in USD.",
        alias="buyVolume4H",
    )
    buy_volume24_h: Optional[StrictStr] = Field(
        default=None,
        description="Buy volume in the last 24 hours, denominated in USD.",
        alias="buyVolume24H",
    )
    sell_volume5_m: Optional[StrictStr] = Field(
        default=None,
        description="Sell volume in the last 5 minutes, denominated in USD.",
        alias="sellVolume5M",
    )
    sell_volume1_h: Optional[StrictStr] = Field(
        default=None,
        description="Sell volume in the last 1 hour, denominated in USD.",
        alias="sellVolume1H",
    )
    sell_volume4_h: Optional[StrictStr] = Field(
        default=None,
        description="Sell volume in the last 4 hours, denominated in USD.",
        alias="sellVolume4H",
    )
    sell_volume24_h: Optional[StrictStr] = Field(
        default=None,
        description="Sell volume in the last 24 hours, denominated in USD.",
        alias="sellVolume24H",
    )
    txs5_m: Optional[StrictInt] = Field(
        default=None,
        description="Number of transactions in the last 5 minutes.",
        alias="txs5M",
    )
    txs1_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of transactions in the last 1 hour.",
        alias="txs1H",
    )
    txs4_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of transactions in the last 4 hours.",
        alias="txs4H",
    )
    txs24_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of transactions in the last 24 hours.",
        alias="txs24H",
    )
    buy_txs5_m: Optional[StrictInt] = Field(
        default=None,
        description="Number of buy transactions in the last 5 minutes.",
        alias="buyTxs5M",
    )
    buy_txs1_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of buy transactions in the last 1 hour.",
        alias="buyTxs1H",
    )
    buy_txs4_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of buy transactions in the last 4 hours.",
        alias="buyTxs4H",
    )
    buy_txs24_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of buy transactions in the last 24 hours.",
        alias="buyTxs24H",
    )
    sell_txs5_m: Optional[StrictInt] = Field(
        default=None,
        description="Number of sell transactions in the last 5 minutes.",
        alias="sellTxs5M",
    )
    sell_txs1_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of sell transactions in the last 1 hour.",
        alias="sellTxs1H",
    )
    sell_txs4_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of sell transactions in the last 4 hours.",
        alias="sellTxs4H",
    )
    sell_txs24_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of sell transactions in the last 24 hours.",
        alias="sellTxs24H",
    )
    max_price: Optional[StrictStr] = Field(
        default=None,
        description="24-hour high price, denominated in USD.",
        alias="maxPrice",
    )
    min_price: Optional[StrictStr] = Field(
        default=None,
        description="24-hour low price, denominated in USD.",
        alias="minPrice",
    )
    circ_supply: Optional[StrictStr] = Field(
        default=None,
        description="Current circulating supply of the token.",
        alias="circSupply",
    )
    liquidity: Optional[StrictStr] = Field(
        default=None, description="Token liquidity, denominated in USD."
    )
    holders: Optional[StrictInt] = Field(
        default=None, description="Number of holding addresses."
    )
    bn_volume5_m: Optional[StrictStr] = Field(
        default=None,
        description="Trading volume from Binance MPC wallets via Binance Web3 DEX in the last 5 minutes, denominated in USD.",
        alias="bnVolume5M",
    )
    bn_volume1_h: Optional[StrictStr] = Field(
        default=None,
        description="Trading volume from Binance MPC wallets via Binance Web3 DEX in the last 1 hour, denominated in USD.",
        alias="bnVolume1H",
    )
    bn_volume4_h: Optional[StrictStr] = Field(
        default=None,
        description="Trading volume from Binance MPC wallets via Binance Web3 DEX in the last 4 hours, denominated in USD.",
        alias="bnVolume4H",
    )
    bn_volume24_h: Optional[StrictStr] = Field(
        default=None,
        description="Trading volume from Binance MPC wallets via Binance Web3 DEX in the last 24 hours, denominated in USD.",
        alias="bnVolume24H",
    )
    bn_buy_volume5_m: Optional[StrictStr] = Field(
        default=None,
        description="Buy volume from Binance MPC wallets via Binance Web3 DEX in the last 5 minutes, denominated in USD.",
        alias="bnBuyVolume5M",
    )
    bn_buy_volume1_h: Optional[StrictStr] = Field(
        default=None,
        description="Buy volume from Binance MPC wallets via Binance Web3 DEX in the last 1 hour, denominated in USD.",
        alias="bnBuyVolume1H",
    )
    bn_buy_volume4_h: Optional[StrictStr] = Field(
        default=None,
        description="Buy volume from Binance MPC wallets via Binance Web3 DEX in the last 4 hours, denominated in USD.",
        alias="bnBuyVolume4H",
    )
    bn_buy_volume24_h: Optional[StrictStr] = Field(
        default=None,
        description="Buy volume from Binance MPC wallets via Binance Web3 DEX in the last 24 hours, denominated in USD.",
        alias="bnBuyVolume24H",
    )
    bn_sell_volume5_m: Optional[StrictStr] = Field(
        default=None,
        description="Sell volume from Binance MPC wallets via Binance Web3 DEX in the last 5 minutes, denominated in USD.",
        alias="bnSellVolume5M",
    )
    bn_sell_volume1_h: Optional[StrictStr] = Field(
        default=None,
        description="Sell volume from Binance MPC wallets via Binance Web3 DEX in the last 1 hour, denominated in USD.",
        alias="bnSellVolume1H",
    )
    bn_sell_volume4_h: Optional[StrictStr] = Field(
        default=None,
        description="Sell volume from Binance MPC wallets via Binance Web3 DEX in the last 4 hours, denominated in USD.",
        alias="bnSellVolume4H",
    )
    bn_sell_volume24_h: Optional[StrictStr] = Field(
        default=None,
        description="Sell volume from Binance MPC wallets via Binance Web3 DEX in the last 24 hours, denominated in USD.",
        alias="bnSellVolume24H",
    )
    bn_txs5_m: Optional[StrictInt] = Field(
        default=None,
        description="Number of transactions from Binance MPC wallets via Binance Web3 DEX in the last 5 minutes.",
        alias="bnTxs5M",
    )
    bn_txs1_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of transactions from Binance MPC wallets via Binance Web3 DEX in the last 1 hour.",
        alias="bnTxs1H",
    )
    bn_txs4_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of transactions from Binance MPC wallets via Binance Web3 DEX in the last 4 hours.",
        alias="bnTxs4H",
    )
    bn_txs24_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of transactions from Binance MPC wallets via Binance Web3 DEX in the last 24 hours.",
        alias="bnTxs24H",
    )
    bn_buy_txs5_m: Optional[StrictInt] = Field(
        default=None,
        description="Number of buy transactions from Binance MPC wallets via Binance Web3 DEX in the last 5 minutes.",
        alias="bnBuyTxs5M",
    )
    bn_buy_txs1_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of buy transactions from Binance MPC wallets via Binance Web3 DEX in the last 1 hour.",
        alias="bnBuyTxs1H",
    )
    bn_buy_txs4_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of buy transactions from Binance MPC wallets via Binance Web3 DEX in the last 4 hours.",
        alias="bnBuyTxs4H",
    )
    bn_buy_txs24_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of buy transactions from Binance MPC wallets via Binance Web3 DEX in the last 24 hours.",
        alias="bnBuyTxs24H",
    )
    bn_sell_txs5_m: Optional[StrictInt] = Field(
        default=None,
        description="Number of sell transactions from Binance MPC wallets via Binance Web3 DEX in the last 5 minutes.",
        alias="bnSellTxs5M",
    )
    bn_sell_txs1_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of sell transactions from Binance MPC wallets via Binance Web3 DEX in the last 1 hour.",
        alias="bnSellTxs1H",
    )
    bn_sell_txs4_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of sell transactions from Binance MPC wallets via Binance Web3 DEX in the last 4 hours.",
        alias="bnSellTxs4H",
    )
    bn_sell_txs24_h: Optional[StrictInt] = Field(
        default=None,
        description="Number of sell transactions from Binance MPC wallets via Binance Web3 DEX in the last 24 hours.",
        alias="bnSellTxs24H",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "binanceChainId",
        "tokenContractAddress",
        "price",
        "time",
        "marketCap",
        "priceChange5M",
        "priceChange1H",
        "priceChange4H",
        "priceChange24H",
        "volume5M",
        "volume1H",
        "volume4H",
        "volume24H",
        "buyVolume5M",
        "buyVolume1H",
        "buyVolume4H",
        "buyVolume24H",
        "sellVolume5M",
        "sellVolume1H",
        "sellVolume4H",
        "sellVolume24H",
        "txs5M",
        "txs1H",
        "txs4H",
        "txs24H",
        "buyTxs5M",
        "buyTxs1H",
        "buyTxs4H",
        "buyTxs24H",
        "sellTxs5M",
        "sellTxs1H",
        "sellTxs4H",
        "sellTxs24H",
        "maxPrice",
        "minPrice",
        "circSupply",
        "liquidity",
        "holders",
        "bnVolume5M",
        "bnVolume1H",
        "bnVolume4H",
        "bnVolume24H",
        "bnBuyVolume5M",
        "bnBuyVolume1H",
        "bnBuyVolume4H",
        "bnBuyVolume24H",
        "bnSellVolume5M",
        "bnSellVolume1H",
        "bnSellVolume4H",
        "bnSellVolume24H",
        "bnTxs5M",
        "bnTxs1H",
        "bnTxs4H",
        "bnTxs24H",
        "bnBuyTxs5M",
        "bnBuyTxs1H",
        "bnBuyTxs4H",
        "bnBuyTxs24H",
        "bnSellTxs5M",
        "bnSellTxs1H",
        "bnSellTxs4H",
        "bnSellTxs24H",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetTokenTradingInfoResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetTokenTradingInfoResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "binanceChainId": obj.get("binanceChainId"),
                "tokenContractAddress": obj.get("tokenContractAddress"),
                "price": obj.get("price"),
                "time": obj.get("time"),
                "marketCap": obj.get("marketCap"),
                "priceChange5M": obj.get("priceChange5M"),
                "priceChange1H": obj.get("priceChange1H"),
                "priceChange4H": obj.get("priceChange4H"),
                "priceChange24H": obj.get("priceChange24H"),
                "volume5M": obj.get("volume5M"),
                "volume1H": obj.get("volume1H"),
                "volume4H": obj.get("volume4H"),
                "volume24H": obj.get("volume24H"),
                "buyVolume5M": obj.get("buyVolume5M"),
                "buyVolume1H": obj.get("buyVolume1H"),
                "buyVolume4H": obj.get("buyVolume4H"),
                "buyVolume24H": obj.get("buyVolume24H"),
                "sellVolume5M": obj.get("sellVolume5M"),
                "sellVolume1H": obj.get("sellVolume1H"),
                "sellVolume4H": obj.get("sellVolume4H"),
                "sellVolume24H": obj.get("sellVolume24H"),
                "txs5M": obj.get("txs5M"),
                "txs1H": obj.get("txs1H"),
                "txs4H": obj.get("txs4H"),
                "txs24H": obj.get("txs24H"),
                "buyTxs5M": obj.get("buyTxs5M"),
                "buyTxs1H": obj.get("buyTxs1H"),
                "buyTxs4H": obj.get("buyTxs4H"),
                "buyTxs24H": obj.get("buyTxs24H"),
                "sellTxs5M": obj.get("sellTxs5M"),
                "sellTxs1H": obj.get("sellTxs1H"),
                "sellTxs4H": obj.get("sellTxs4H"),
                "sellTxs24H": obj.get("sellTxs24H"),
                "maxPrice": obj.get("maxPrice"),
                "minPrice": obj.get("minPrice"),
                "circSupply": obj.get("circSupply"),
                "liquidity": obj.get("liquidity"),
                "holders": obj.get("holders"),
                "bnVolume5M": obj.get("bnVolume5M"),
                "bnVolume1H": obj.get("bnVolume1H"),
                "bnVolume4H": obj.get("bnVolume4H"),
                "bnVolume24H": obj.get("bnVolume24H"),
                "bnBuyVolume5M": obj.get("bnBuyVolume5M"),
                "bnBuyVolume1H": obj.get("bnBuyVolume1H"),
                "bnBuyVolume4H": obj.get("bnBuyVolume4H"),
                "bnBuyVolume24H": obj.get("bnBuyVolume24H"),
                "bnSellVolume5M": obj.get("bnSellVolume5M"),
                "bnSellVolume1H": obj.get("bnSellVolume1H"),
                "bnSellVolume4H": obj.get("bnSellVolume4H"),
                "bnSellVolume24H": obj.get("bnSellVolume24H"),
                "bnTxs5M": obj.get("bnTxs5M"),
                "bnTxs1H": obj.get("bnTxs1H"),
                "bnTxs4H": obj.get("bnTxs4H"),
                "bnTxs24H": obj.get("bnTxs24H"),
                "bnBuyTxs5M": obj.get("bnBuyTxs5M"),
                "bnBuyTxs1H": obj.get("bnBuyTxs1H"),
                "bnBuyTxs4H": obj.get("bnBuyTxs4H"),
                "bnBuyTxs24H": obj.get("bnBuyTxs24H"),
                "bnSellTxs5M": obj.get("bnSellTxs5M"),
                "bnSellTxs1H": obj.get("bnSellTxs1H"),
                "bnSellTxs4H": obj.get("bnSellTxs4H"),
                "bnSellTxs24H": obj.get("bnSellTxs24H"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
