"""
Binance Pay REST API

OpenAPI Specification for the Binance Pay REST API
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
import pytest
import requests

from unittest.mock import MagicMock, patch
from urllib.parse import parse_qs

from binance_common.configuration import ConfigurationRestAPI
from binance_common.utils import is_one_of_model

from binance_sdk_pay.rest_api.api import PayApi
from binance_sdk_pay.rest_api.models import GetPayTradeHistoryResponse


class TestPayApi:
    @pytest.fixture(autouse=True)
    def setup_client(self):
        """Setup a client instance with mocked session before each test method."""
        self.mock_session = MagicMock(spec=requests.Session)
        config = ConfigurationRestAPI(
            api_key="test-api-key",
            api_secret="test-api-secret",
        )
        self.client = PayApi(configuration=config, session=self.mock_session)

    def set_mock_response(self, data: dict = {}, status_code=200, headers=None):
        """Helper method to setup mock response for the client's session request."""
        if headers is None:
            headers = {}

        mock_response = MagicMock()
        mock_response.status_code = status_code
        mock_response.json.return_value = data
        mock_response.text = json.dumps(data)
        mock_response.headers = headers

        self.mock_session.request.return_value = mock_response

    @patch("binance_common.utils.get_signature")
    def test_get_pay_trade_history_success(self, mock_get_signature):
        """Test get_pay_trade_history() successfully with required parameters only."""

        expected_response = {
            "code": "000000",
            "message": "success",
            "data": [
                {
                    "orderType": "C2C",
                    "transactionId": "M_P_71505104267788288",
                    "transactionTime": 1610090460133,
                    "amount": "23.72469206",
                    "currency": "BNB",
                    "walletType": 1,
                    "walletTypes": [1, 2],
                    "fundsDetail": [
                        {
                            "currency": "USDT",
                            "amount": "1.2",
                            "walletAssetCost": [{"1": "0.6"}, {"2": "0.6"}],
                        },
                        {
                            "currency": "ETH",
                            "amount": "0.0001",
                            "walletAssetCost": [{"1": "0.00005"}, {"2": "0.00005"}],
                        },
                    ],
                    "payerInfo": {
                        "name": "Jack",
                        "type": "USER",
                        "binanceId": "12345678",
                    },
                    "receiverInfo": {
                        "name": "Alan",
                        "type": "MERCHANT",
                        "email": "alan@binance.com",
                        "binanceId": "34355667",
                        "accountId": "21326891",
                        "countryCode": "1",
                        "phoneNumber": "8057651210",
                        "mobileCode": "US",
                        "extend": {
                            "institutionName": "",
                            "cardNumber": "",
                            "digitalWalletId": "",
                        },
                    },
                }
            ],
            "success": True,
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.get_pay_trade_history()

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        self.mock_session.request.assert_called_once()
        mock_get_signature.assert_called_once()

        assert "url" in request_kwargs
        assert "signature" in parse_qs(request_kwargs["params"])
        assert "/sapi/v1/pay/transactions" in request_kwargs["url"]
        assert request_kwargs["method"] == "GET"

        assert response is not None
        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(GetPayTradeHistoryResponse)

        if is_list and not is_flat_list:
            expected = expected_response
        elif is_oneof or is_list:
            expected = GetPayTradeHistoryResponse.from_dict(expected_response)
        else:
            expected = GetPayTradeHistoryResponse.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    @patch("binance_common.utils.get_signature")
    def test_get_pay_trade_history_success_with_optional_params(
        self, mock_get_signature
    ):
        """Test get_pay_trade_history() successfully with optional parameters."""

        params = {
            "start_time": 1623319461670,
            "end_time": 1641782889000,
            "limit": 100,
            "recv_window": 5000,
        }

        expected_response = {
            "code": "000000",
            "message": "success",
            "data": [
                {
                    "orderType": "C2C",
                    "transactionId": "M_P_71505104267788288",
                    "transactionTime": 1610090460133,
                    "amount": "23.72469206",
                    "currency": "BNB",
                    "walletType": 1,
                    "walletTypes": [1, 2],
                    "fundsDetail": [
                        {
                            "currency": "USDT",
                            "amount": "1.2",
                            "walletAssetCost": [{"1": "0.6"}, {"2": "0.6"}],
                        },
                        {
                            "currency": "ETH",
                            "amount": "0.0001",
                            "walletAssetCost": [{"1": "0.00005"}, {"2": "0.00005"}],
                        },
                    ],
                    "payerInfo": {
                        "name": "Jack",
                        "type": "USER",
                        "binanceId": "12345678",
                    },
                    "receiverInfo": {
                        "name": "Alan",
                        "type": "MERCHANT",
                        "email": "alan@binance.com",
                        "binanceId": "34355667",
                        "accountId": "21326891",
                        "countryCode": "1",
                        "phoneNumber": "8057651210",
                        "mobileCode": "US",
                        "extend": {
                            "institutionName": "",
                            "cardNumber": "",
                            "digitalWalletId": "",
                        },
                    },
                }
            ],
            "success": True,
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.get_pay_trade_history(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        assert "url" in request_kwargs
        assert "signature" in parse_qs(request_kwargs["params"])
        assert "/sapi/v1/pay/transactions" in request_kwargs["url"]
        assert request_kwargs["method"] == "GET"

        self.mock_session.request.assert_called_once()
        assert response is not None
        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(GetPayTradeHistoryResponse)

        if is_list and not is_flat_list:
            expected = expected_response
        elif is_oneof or is_list:
            expected = GetPayTradeHistoryResponse.from_dict(expected_response)
        else:
            expected = GetPayTradeHistoryResponse.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    def test_get_pay_trade_history_server_error(self):
        """Test that get_pay_trade_history() raises an error when the server returns an error."""

        mock_error = Exception("ResponseError")
        self.client.get_pay_trade_history = MagicMock(side_effect=mock_error)

        with pytest.raises(Exception, match="ResponseError"):
            self.client.get_pay_trade_history()
