"""
Spot WebSocket API

Access market data, manage accounts, and trade on Binance Spot.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from binance_common.errors import RequiredError
from binance_common.models import WebsocketApiResponse
from binance_common.signature import Signers
from binance_common.websocket import WebSocketAPIBase

from ..models import AccountCommissionResponse
from ..models import AccountRateLimitsOrdersResponse
from ..models import AccountStatusResponse
from ..models import AllOrderListsResponse
from ..models import AllOrdersResponse
from ..models import MyAllocationsResponse
from ..models import MyFiltersResponse
from ..models import MyPreventedMatchesResponse
from ..models import MyTradesResponse
from ..models import OpenOrderListsStatusResponse
from ..models import OpenOrdersStatusResponse
from ..models import OrderAmendmentsResponse
from ..models import OrderListStatusResponse
from ..models import OrderStatusResponse


from typing import Optional, Union


class AccountApi:
    """API Client for AccountApi endpoints."""

    def __init__(
        self,
        websocket_api: WebSocketAPIBase,
        signer: Signers = None,
    ) -> None:
        self.websocket_api = websocket_api
        self.signer = signer

    async def account_commission(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
    ) -> WebsocketApiResponse[AccountCommissionResponse]:
        """
            Account Commission Rates (USER_DATA)
            /account.commission
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-api/account#account-commission

            Get current account commission rates.

        Weight(IP): 20

        Security Type: USER_DATA

        Notes:
        **Data Source:** Database

            Args:
                    symbol (Union[str, None]):
                    id (Optional[str] = None): Client-generated request identifier.

            Returns:
                WebsocketApiResponse[AccountCommissionResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        params = {
            "symbol": symbol,
            **({"id": id} if id is not None else {}),
        }

        payload = {
            "method": "/account.commission".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload,
            response_model=AccountCommissionResponse,
            signer=self.signer,
        )

    async def account_rate_limits_orders(
        self,
        id: Optional[str] = None,
        recv_window: Optional[float] = None,
    ) -> WebsocketApiResponse[AccountRateLimitsOrdersResponse]:
        """
            Unfilled Order Count (USER_DATA)
            /account.rateLimits.orders
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-api/account#account-rate-limits-orders

            Query your current unfilled order count for all intervals.

        Weight(IP): 40

        Security Type: USER_DATA

        Notes:
        **Data Source:** Memory

            Args:
                    id (Optional[str] = None): Client-generated request identifier.
                    recv_window (Optional[float] = None): Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.

            Returns:
                WebsocketApiResponse[AccountRateLimitsOrdersResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        params = {
            **({"id": id} if id is not None else {}),
            **({"recv_window": recv_window} if recv_window is not None else {}),
        }

        payload = {
            "method": "/account.rateLimits.orders".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload,
            response_model=AccountRateLimitsOrdersResponse,
            signer=self.signer,
        )

    async def account_status(
        self,
        id: Optional[str] = None,
        omit_zero_balances: Optional[bool] = None,
        recv_window: Optional[float] = None,
    ) -> WebsocketApiResponse[AccountStatusResponse]:
        """
            Account information (USER_DATA)
            /account.status
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-api/account#account-status

            Query information about your account.

        Weight(IP): 20

        Security Type: USER_DATA

        Notes:
        **Data Source:** Memory => Database

            Args:
                    id (Optional[str] = None): Client-generated request identifier.
                    omit_zero_balances (Optional[bool] = None): When set to `true`, emits only the non-zero balances of an account. Default value: `false`.
                    recv_window (Optional[float] = None): Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.

            Returns:
                WebsocketApiResponse[AccountStatusResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        params = {
            **({"id": id} if id is not None else {}),
            **(
                {"omit_zero_balances": omit_zero_balances}
                if omit_zero_balances is not None
                else {}
            ),
            **({"recv_window": recv_window} if recv_window is not None else {}),
        }

        payload = {
            "method": "/account.status".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload, response_model=AccountStatusResponse, signer=self.signer
        )

    async def all_order_lists(
        self,
        id: Optional[str] = None,
        from_id: Optional[int] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        limit: Optional[int] = None,
        recv_window: Optional[float] = None,
    ) -> WebsocketApiResponse[AllOrderListsResponse]:
        """
            Account order list history (USER_DATA)
            /allOrderLists
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-api/account#all-order-lists

            Query information about all your order lists, filtered by time range.

        Weight(IP): 20

        Security Type: USER_DATA

        Notes:
        **Data Source:** Database

        Notes:
        * If `startTime` and/or `endTime` are specified, `fromId` is ignored.
          Order lists are filtered by `transactionTime` of the last order list execution status update.
        * If `fromId` is specified, return order lists with order list ID >= `fromId`.
        * If no condition is specified, the most recent order lists are returned.
        * The time between `startTime` and `endTime` can't be longer than 24 hours.

            Args:
                    id (Optional[str] = None): Client-generated request identifier.
                    from_id (Optional[int] = None): Order list ID to begin at
                    start_time (Optional[int] = None): Timestamp in ms
                    end_time (Optional[int] = None): Timestamp in ms
                    limit (Optional[int] = None): Default: 500; Maximum: 1000
                    recv_window (Optional[float] = None): Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.

            Returns:
                WebsocketApiResponse[AllOrderListsResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        params = {
            **({"id": id} if id is not None else {}),
            **({"from_id": from_id} if from_id is not None else {}),
            **({"start_time": start_time} if start_time is not None else {}),
            **({"end_time": end_time} if end_time is not None else {}),
            **({"limit": limit} if limit is not None else {}),
            **({"recv_window": recv_window} if recv_window is not None else {}),
        }

        payload = {
            "method": "/allOrderLists".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload, response_model=AllOrderListsResponse, signer=self.signer
        )

    async def all_orders(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
        order_id: Optional[int] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        limit: Optional[int] = None,
        recv_window: Optional[float] = None,
    ) -> WebsocketApiResponse[AllOrdersResponse]:
        """
            Account order history (USER_DATA)
            /allOrders
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-api/account#all-orders

            Query information about all your orders – active, canceled, filled – filtered by time range.

        Weight(IP): 20

        Security Type: USER_DATA

        Notes:
        **Data Source:** Database

        Notes:

        * If `startTime` and/or `endTime` are specified, `orderId` is ignored.

          Orders are filtered by `time` of the last execution status update.

        * If `orderId` is specified, return orders with order ID >= `orderId`.

        * If no condition is specified, the most recent orders are returned.

        * For some historical orders the `cummulativeQuoteQty` response field may be negative,
          meaning the data is not available at this time.

        * The time between `startTime` and `endTime` can't be longer than 24 hours.

            Args:
                    symbol (Union[str, None]):
                    id (Optional[str] = None): Client-generated request identifier.
                    order_id (Optional[int] = None): Order ID to begin at
                    start_time (Optional[int] = None): Timestamp in ms
                    end_time (Optional[int] = None): Timestamp in ms
                    limit (Optional[int] = None): Default: 500; Maximum: 1000
                    recv_window (Optional[float] = None): Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.

            Returns:
                WebsocketApiResponse[AllOrdersResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        params = {
            "symbol": symbol,
            **({"id": id} if id is not None else {}),
            **({"order_id": order_id} if order_id is not None else {}),
            **({"start_time": start_time} if start_time is not None else {}),
            **({"end_time": end_time} if end_time is not None else {}),
            **({"limit": limit} if limit is not None else {}),
            **({"recv_window": recv_window} if recv_window is not None else {}),
        }

        payload = {
            "method": "/allOrders".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload, response_model=AllOrdersResponse, signer=self.signer
        )

    async def my_allocations(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        from_allocation_id: Optional[int] = None,
        limit: Optional[int] = None,
        order_id: Optional[int] = None,
        recv_window: Optional[float] = None,
    ) -> WebsocketApiResponse[MyAllocationsResponse]:
        """
            Account allocations (USER_DATA)
            /myAllocations
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-api/account#my-allocations

            Retrieves allocations resulting from SOR order placement.

        Weight(IP): 20

        Security Type: USER_DATA

        Notes:
        **Data Source:** Database

        Supported parameter combinations:

        Parameters                                  | Response |
        ------------------------------------------- | -------- |
        `symbol`                                    | allocations from oldest to newest |
        `symbol` + `startTime`                      | oldest allocations since `startTime` |
        `symbol` + `endTime`                        | newest allocations until `endTime` |
        `symbol` + `startTime` + `endTime`          | allocations within the time range |
        `symbol` + `fromAllocationId`               | allocations by allocation ID |
        `symbol` + `orderId`                        | allocations related to an order starting with oldest |
        `symbol` + `orderId` + `fromAllocationId`   | allocations related to an order by allocation ID |

        **Note:** The time between `startTime` and `endTime` can't be longer than 24 hours.

            Args:
                    symbol (Union[str, None]):
                    id (Optional[str] = None): Client-generated request identifier.
                    start_time (Optional[int] = None): Timestamp in ms
                    end_time (Optional[int] = None): Timestamp in ms
                    from_allocation_id (Optional[int] = None): Allocation ID to begin at
                    limit (Optional[int] = None): Default: 500; Maximum: 1000
                    order_id (Optional[int] = None): Order ID
                    recv_window (Optional[float] = None): Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.

            Returns:
                WebsocketApiResponse[MyAllocationsResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        params = {
            "symbol": symbol,
            **({"id": id} if id is not None else {}),
            **({"start_time": start_time} if start_time is not None else {}),
            **({"end_time": end_time} if end_time is not None else {}),
            **(
                {"from_allocation_id": from_allocation_id}
                if from_allocation_id is not None
                else {}
            ),
            **({"limit": limit} if limit is not None else {}),
            **({"order_id": order_id} if order_id is not None else {}),
            **({"recv_window": recv_window} if recv_window is not None else {}),
        }

        payload = {
            "method": "/myAllocations".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload, response_model=MyAllocationsResponse, signer=self.signer
        )

    async def my_filters(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
        recv_window: Optional[float] = None,
    ) -> WebsocketApiResponse[MyFiltersResponse]:
        """
            Query Relevant Filters (USER_DATA)
            /myFilters
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-api/account#my-filters

            Retrieves the list of [filters](/products/spot/filters) relevant to an account on a given symbol. This is the only method
        that shows if an account has [`MAX_ASSET`](/products/spot/filters#max_asset) filters applied to it.

        Weight(IP): 40

        Security Type: USER_DATA

        Notes:
        **Data Source:** Memory

            Args:
                    symbol (Union[str, None]):
                    id (Optional[str] = None): Client-generated request identifier.
                    recv_window (Optional[float] = None): Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.

            Returns:
                WebsocketApiResponse[MyFiltersResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        params = {
            "symbol": symbol,
            **({"id": id} if id is not None else {}),
            **({"recv_window": recv_window} if recv_window is not None else {}),
        }

        payload = {
            "method": "/myFilters".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload, response_model=MyFiltersResponse, signer=self.signer
        )

    async def my_prevented_matches(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
        prevented_match_id: Optional[int] = None,
        order_id: Optional[int] = None,
        from_prevented_match_id: Optional[int] = None,
        limit: Optional[int] = None,
        recv_window: Optional[float] = None,
    ) -> WebsocketApiResponse[MyPreventedMatchesResponse]:
        """
            Account prevented matches (USER_DATA)
            /myPreventedMatches
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-api/account#my-prevented-matches

            Displays the list of orders that were expired due to STP.

        These are the combinations supported:

        * `symbol` + `preventedMatchId`
        * `symbol` + `orderId`
        * `symbol` + `orderId` + `fromPreventedMatchId` (`limit` will default to 500)
        * `symbol` + `orderId` + `fromPreventedMatchId` + `limit`

        Weight: Case                            | Weight
        ----                            | -----
        If `symbol` is invalid          | 2
        Querying by `preventedMatchId`  | 2
        Querying by `orderId`           | 20

        Security Type: USER_DATA

        Notes:
        **Data Source:** Database

            Args:
                    symbol (Union[str, None]):
                    id (Optional[str] = None): Client-generated request identifier.
                    prevented_match_id (Optional[int] = None): Prevented match ID
                    order_id (Optional[int] = None): Order ID
                    from_prevented_match_id (Optional[int] = None): Prevented match ID to begin at
                    limit (Optional[int] = None): Default: 500; Maximum: 1000
                    recv_window (Optional[float] = None): Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.

            Returns:
                WebsocketApiResponse[MyPreventedMatchesResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        params = {
            "symbol": symbol,
            **({"id": id} if id is not None else {}),
            **(
                {"prevented_match_id": prevented_match_id}
                if prevented_match_id is not None
                else {}
            ),
            **({"order_id": order_id} if order_id is not None else {}),
            **(
                {"from_prevented_match_id": from_prevented_match_id}
                if from_prevented_match_id is not None
                else {}
            ),
            **({"limit": limit} if limit is not None else {}),
            **({"recv_window": recv_window} if recv_window is not None else {}),
        }

        payload = {
            "method": "/myPreventedMatches".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload,
            response_model=MyPreventedMatchesResponse,
            signer=self.signer,
        )

    async def my_trades(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
        order_id: Optional[int] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        from_id: Optional[int] = None,
        limit: Optional[int] = None,
        recv_window: Optional[float] = None,
    ) -> WebsocketApiResponse[MyTradesResponse]:
        """
            Account trade history (USER_DATA)
            /myTrades
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-api/account#my-trades

            Query information about all your trades, filtered by time range.

        Weight: Condition| Weight|
        ---| ---
        |Without orderId|20|
        |With orderId|5|

        Security Type: USER_DATA

        Notes:
        Data Source: Memory => Database

        Notes:
        - If `fromId` is specified, return trades with trade ID >= `fromId`.
        - If `startTime` and/or `endTime` are specified, trades are filtered by execution time (`time`).
        - `fromId` cannot be used together with `startTime` and `endTime`.
        - If `orderId` is specified, only trades related to that order are returned.
        - `startTime` and `endTime` cannot be used together with `orderId`.
        - If no condition is specified, the most recent trades are returned.
        - The time between `startTime` and `endTime` can't be longer than 24 hours.

            Args:
                    symbol (Union[str, None]):
                    id (Optional[str] = None): Client-generated request identifier.
                    order_id (Optional[int] = None): This can only be used in combination with `symbol`.
                    start_time (Optional[int] = None): Timestamp in ms
                    end_time (Optional[int] = None): Timestamp in ms
                    from_id (Optional[int] = None): First trade ID to query
                    limit (Optional[int] = None): Default: 500; Maximum: 1000
                    recv_window (Optional[float] = None): Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.

            Returns:
                WebsocketApiResponse[MyTradesResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        params = {
            "symbol": symbol,
            **({"id": id} if id is not None else {}),
            **({"order_id": order_id} if order_id is not None else {}),
            **({"start_time": start_time} if start_time is not None else {}),
            **({"end_time": end_time} if end_time is not None else {}),
            **({"from_id": from_id} if from_id is not None else {}),
            **({"limit": limit} if limit is not None else {}),
            **({"recv_window": recv_window} if recv_window is not None else {}),
        }

        payload = {
            "method": "/myTrades".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload, response_model=MyTradesResponse, signer=self.signer
        )

    async def open_order_lists_status(
        self,
        id: Optional[str] = None,
        recv_window: Optional[float] = None,
    ) -> WebsocketApiResponse[OpenOrderListsStatusResponse]:
        """
            Current open Order lists (USER_DATA)
            /openOrderLists.status
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-api/account#open-order-lists-status

            Query execution status of all open order lists.

        If you need to continuously monitor order status updates, please consider using WebSocket Streams:

        * `userDataStream.subscribe` if on an authenticated session
        * `userDataStream.subscribe.signature` if subscribing through signature subscription

        Weight(IP): 6

        Security Type: USER_DATA

        Notes:
        **Data Source:** Memory -> Database

            Args:
                    id (Optional[str] = None): Client-generated request identifier.
                    recv_window (Optional[float] = None): Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.

            Returns:
                WebsocketApiResponse[OpenOrderListsStatusResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        params = {
            **({"id": id} if id is not None else {}),
            **({"recv_window": recv_window} if recv_window is not None else {}),
        }

        payload = {
            "method": "/openOrderLists.status".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload,
            response_model=OpenOrderListsStatusResponse,
            signer=self.signer,
        )

    async def open_orders_status(
        self,
        id: Optional[str] = None,
        symbol: Optional[str] = None,
        recv_window: Optional[float] = None,
    ) -> WebsocketApiResponse[OpenOrdersStatusResponse]:
        """
            Current open orders (USER_DATA)
            /openOrders.status
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-api/account#open-orders-status

            Query execution status of all open orders.

        If you need to continuously monitor order status updates, please consider using WebSocket Streams:

        * `userDataStream.subscribe` if on an authenticated session
        * `userDataStream.subscribe.signature` if subscribing through signature subscription

        Weight: | Parameter | Weight |
        | --------- | ------ |
        | `symbol`  |      6 |
        | none      |     80 |

        Security Type: USER_DATA

        Notes:
        Data Source: Memory => Database

            Args:
                    id (Optional[str] = None): Client-generated request identifier.
                    symbol (Optional[str] = None): If omitted, open orders for all symbols are returned
                    recv_window (Optional[float] = None): Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.

            Returns:
                WebsocketApiResponse[OpenOrdersStatusResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        params = {
            **({"id": id} if id is not None else {}),
            **({"symbol": symbol} if symbol is not None else {}),
            **({"recv_window": recv_window} if recv_window is not None else {}),
        }

        payload = {
            "method": "/openOrders.status".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload, response_model=OpenOrdersStatusResponse, signer=self.signer
        )

    async def order_amendments(
        self,
        symbol: Union[str, None],
        order_id: Union[int, None],
        id: Optional[str] = None,
        from_execution_id: Optional[int] = None,
        limit: Optional[int] = None,
        recv_window: Optional[float] = None,
    ) -> WebsocketApiResponse[OrderAmendmentsResponse]:
        """
            Query Order Amendments (USER_DATA)
            /order.amendments
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-api/account#order-amendments

            Queries all amendments of a single order.

        Weight(IP): 4

        Security Type: USER_DATA

        Notes:
        **Data Source:** Database

            Args:
                    symbol (Union[str, None]):
                    order_id (Union[int, None]): Order ID
                    id (Optional[str] = None): Client-generated request identifier.
                    from_execution_id (Optional[int] = None): Execution ID to begin at
                    limit (Optional[int] = None): Default: 500; Maximum: 1000
                    recv_window (Optional[float] = None): Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.

            Returns:
                WebsocketApiResponse[OrderAmendmentsResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )
        if order_id is None:
            raise RequiredError(
                field="order_id", error_message="Missing required parameter 'order_id'"
            )

        params = {
            "symbol": symbol,
            "order_id": order_id,
            **({"id": id} if id is not None else {}),
            **(
                {"from_execution_id": from_execution_id}
                if from_execution_id is not None
                else {}
            ),
            **({"limit": limit} if limit is not None else {}),
            **({"recv_window": recv_window} if recv_window is not None else {}),
        }

        payload = {
            "method": "/order.amendments".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload, response_model=OrderAmendmentsResponse, signer=self.signer
        )

    async def order_list_status(
        self,
        id: Optional[str] = None,
        orig_client_order_id: Optional[str] = None,
        order_list_id: Optional[int] = None,
        recv_window: Optional[float] = None,
    ) -> WebsocketApiResponse[OrderListStatusResponse]:
        """
            Query Order list (USER_DATA)
            /orderList.status
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-api/account#order-list-status

            Check execution status of an Order list.

        For execution status of individual orders, use `order.status`.

        Weight(IP): 4

        Security Type: USER_DATA

        Notes:
        **Data Source:** Database

        Notes:

        * `origClientOrderId` refers to `listClientOrderId` of the order list itself.

        * If both `origClientOrderId` and `orderListId` parameters are specified,
          only `origClientOrderId` is used and `orderListId` is ignored.

            Args:
                    id (Optional[str] = None): Client-generated request identifier.
                    orig_client_order_id (Optional[str] = None): Query order list by `listClientOrderId`. `orderListId` or `origClientOrderId` must be provided.
                    order_list_id (Optional[int] = None): Query order list by `orderListId`. `orderListId` or `origClientOrderId` must be provided.
                    recv_window (Optional[float] = None): Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.

            Returns:
                WebsocketApiResponse[OrderListStatusResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        params = {
            **({"id": id} if id is not None else {}),
            **(
                {"orig_client_order_id": orig_client_order_id}
                if orig_client_order_id is not None
                else {}
            ),
            **({"order_list_id": order_list_id} if order_list_id is not None else {}),
            **({"recv_window": recv_window} if recv_window is not None else {}),
        }

        payload = {
            "method": "/orderList.status".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload, response_model=OrderListStatusResponse, signer=self.signer
        )

    async def order_status(
        self,
        symbol: Union[str, None],
        id: Optional[str] = None,
        order_id: Optional[int] = None,
        orig_client_order_id: Optional[str] = None,
        recv_window: Optional[float] = None,
    ) -> WebsocketApiResponse[OrderStatusResponse]:
        """
            Query order (USER_DATA)
            /order.status
            https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/ws-api/account#order-status

            Check execution status of an order.

        Weight(IP): 4

        Security Type: USER_DATA

        Notes:
        **Data Source:** Memory => Database

        Notes:

        * If both `orderId` and `origClientOrderId` are provided, the `orderId` is searched first, then the `origClientOrderId` from that result is checked against that order. If both conditions are not met the request will be rejected.

        * For some historical orders the `cummulativeQuoteQty` response field may be negative,
          meaning the data is not available at this time.

            Args:
                    symbol (Union[str, None]):
                    id (Optional[str] = None): Client-generated request identifier.
                    order_id (Optional[int] = None): Lookup order by `orderId`
                    orig_client_order_id (Optional[str] = None): Lookup order by `clientOrderId`
                    recv_window (Optional[float] = None): Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.

            Returns:
                WebsocketApiResponse[OrderStatusResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if symbol is None:
            raise RequiredError(
                field="symbol", error_message="Missing required parameter 'symbol'"
            )

        params = {
            "symbol": symbol,
            **({"id": id} if id is not None else {}),
            **({"order_id": order_id} if order_id is not None else {}),
            **(
                {"orig_client_order_id": orig_client_order_id}
                if orig_client_order_id is not None
                else {}
            ),
            **({"recv_window": recv_window} if recv_window is not None else {}),
        }

        payload = {
            "method": "/order.status".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload, response_model=OrderStatusResponse, signer=self.signer
        )
